import { ToolPageTemplate, buildToolMetadata } from '@/components/tool-page-template';
import { DesignTool } from '@/components/design/design-tool';
import { designToolConfigs } from '@/lib/design-configs';

export const metadata = buildToolMetadata(
  'favicon-generator',
  'Favicon Image Generator',
  'Create favicon-sized images from any image (PNG format).'
);

const relatedSlugs = ['image-resizer', 'image-placeholder-generator', 'svg-to-png', 'svg-optimizer'];

export default function FaviconGeneratorPage() {
  return (
    <ToolPageTemplate
      slug="favicon-generator"
      relatedSlugs={relatedSlugs}
      blurColor="bg-amber-400/20"
      seo={{
        whatIs: `The Favicon Image Generator creates square favicon-sized images (64x64) from any source image. The output is a PNG file with .ico extension — note that true ICO format (which can contain multiple resolutions) is not generated by this tool. For production sites requiring multi-resolution ICO files, you would need a specialized ICO generator. All processing happens locally in your browser.`,
        howTo: [
          'Upload any image (PNG, JPG, WebP, SVG).',
          'Click Generate to create a 64x64 favicon-sized image.',
          'Download the result (PNG format with .ico extension).'
        ],
        benefits: [
          { title: 'Free and unlimited', description: 'Use this tool as many times as you want, completely free with no sign-up required.' },
          { title: 'Privacy first', description: 'All processing happens in your browser. Your data never leaves your device.' },
          { title: 'Quick favicon creation', description: 'Generates a 64x64 square image suitable for basic favicon use.' },
          { title: 'No software needed', description: 'Runs entirely in your browser with no downloads or plugins required.' },
        ],
        faqs: [
          { q: 'Is the Favicon Image Generator free to use?', a: 'Yes, it is completely free with no limits, no registration, and no API keys required.' },
          { q: 'Does it create true multi-resolution ICO files?', a: 'No. The output is a single 64x64 PNG file saved with a .ico extension. True ICO format (which contains multiple image sizes like 16x16, 32x32, 48x48) is not supported by this browser-based tool.' },
          { q: 'Will the .ico file work as a favicon?', a: 'Modern browsers will accept a PNG file with .ico extension for favicon use, but for best compatibility across all browsers and devices, a true multi-resolution ICO file is recommended.' },
          { q: 'Is my data sent to a server?', a: 'No. All processing happens locally in your browser. Your input never leaves your device.' },
        ],
      }}
    >
      <DesignTool config={designToolConfigs['favicon-generator']} />
    </ToolPageTemplate>
  );
}
