import { PageHeader } from '@/components/page-header';

const lastUpdated = 'August 25, 2026';

export default function TermsPage() {
  return (
    <>
      <PageHeader
        eyebrow="Legal"
        title="Terms & Conditions"
        description={`Last updated: ${lastUpdated}`}
      />
      <section className="mx-auto max-w-3xl px-4 pb-24 sm:px-6">
        <div className="space-y-8">
          <div className="rounded-2xl glass-card p-8">
            <p className="text-sm leading-relaxed text-muted-foreground">
              These Terms &amp; Conditions (&ldquo;Terms&rdquo;) govern your
              use of ToolNest (the &ldquo;Site&rdquo;), located at
              freetoolnest.vercel.app, and the free online tools it provides.
              By accessing or using the Site, you agree to be bound by these
              Terms. If you do not agree, please do not use the Site.
            </p>
          </div>

          <TermsSection title="1. Acceptance of Terms">
            <p>
              By using ToolNest, you acknowledge that you have read,
              understood, and agree to these Terms and our{' '}
              <a
                href="/privacy-policy"
                className="text-brand-purple underline underline-offset-2 hover:opacity-80"
              >
                Privacy Policy
              </a>
              . If you do not agree with any part of these Terms, you should
              not access or use the Site.
            </p>
            <p>
              You confirm that you are at least 13 years old, or that you are
              accessing the Site under the supervision of a parent or legal
              guardian.
            </p>
          </TermsSection>

          <TermsSection title="2. Use of ToolNest and Its Free Online Tools">
            <p>
              ToolNest provides a collection of free online tools, including
              PDF, image, audio, video, QR &amp; barcode, text, developer,
              design, SEO, AI, calculator, converter, and productivity tools.
              The Site and all tools are provided free of charge. No
              registration or account is required to use any tool.
            </p>
            <p>
              Most tools process your files and input entirely in your
              browser. Your data does not leave your device unless a specific
              tool explicitly states otherwise.
            </p>
          </TermsSection>

          <TermsSection title="3. Acceptable and Prohibited Use">
            <p>You agree to use ToolNest only for lawful purposes. You agree not to:</p>
            <ul className="ml-4 list-disc space-y-2">
              <li>
                Use the Site or its tools for any illegal, harmful, fraudulent,
                or abusive activity.
              </li>
              <li>
                Attempt to gain unauthorized access to the Site, its servers,
                or any related systems.
              </li>
              <li>
                Interfere with or disrupt the Site, its servers, or the
                experience of other users, including by introducing viruses,
                malware, or harmful code.
              </li>
              <li>
                Scrape, copy, or republish the Site&rsquo;s content or tools
                without permission.
              </li>
              <li>
                Use automated scripts, bots, or crawlers to access the Site in
                a way that sends more requests than a human reasonably could.
              </li>
              <li>
                Use the Site to store, process, or transmit content that
                infringes the rights of others or violates applicable law.
              </li>
            </ul>
          </TermsSection>

          <TermsSection title="4. Tool Output Responsibility and Accuracy Disclaimer">
            <p>
              The tools on ToolNest are provided &ldquo;as is&rdquo; for general
              informational and productivity purposes. We do not guarantee
              that any tool will produce accurate, complete, or reliable
              results, or that it will meet your specific requirements.
            </p>
            <p>
              You are solely responsible for any output generated by the tools
              and for verifying its accuracy before relying on it. ToolNest is
              not liable for any loss or damage arising from the use of, or
              reliance on, tool output &mdash; including converted files,
              generated code, calculated values, or AI-generated text.
            </p>
          </TermsSection>

          <TermsSection title="5. Intellectual Property">
            <p>
              The ToolNest name, logo, site design, text, and the arrangement
              of tools are owned by ToolNest and protected by applicable
              intellectual property laws. You may not copy, reproduce, or
              distribute Site content without permission.
            </p>
            <p>
              Any content you submit &mdash; such as contact messages or
              newsletter email addresses &mdash; remains yours. By submitting
              it, you grant ToolNest a limited license to use it for the
              purpose of responding to you or providing the requested service.
            </p>
          </TermsSection>

          <TermsSection title="6. User-Submitted Contact Information and Messages">
            <p>
              When you contact us through the contact form, we collect the
              name, email, subject, and message you provide. This information
              is used solely to respond to your inquiry and is not shared with
              third parties for marketing. You are responsible for the content
              of your messages and agree not to submit unlawful, abusive, or
              infringing material.
            </p>
          </TermsSection>

          <TermsSection title="7. Third-Party Services and Links">
            <p>
              ToolNest may link to third-party websites or use third-party
              services. We do not control and are not responsible for the
              content, policies, or practices of any third-party site. You
              acknowledge that ToolNest is not liable for any damage or loss
              caused by your use of third-party services.
            </p>
          </TermsSection>

          <TermsSection title="8. Advertising">
            <p>
              ToolNest displays advertisements served by Google AdSense and
              other advertising partners. These parties may use cookies to
              serve ads based on your visits to this and other websites. We
              do not control which ads are shown and are not responsible for
              the content of third-party advertisements. Your interactions
              with ads are governed by the respective advertiser&rsquo;s
              terms.
            </p>
          </TermsSection>

          <TermsSection title="9. Privacy">
            <p>
              Your use of ToolNest is also governed by our{' '}
              <a
                href="/privacy-policy"
                className="text-brand-purple underline underline-offset-2 hover:opacity-80"
              >
                Privacy Policy
              </a>
              , which describes how we collect, use, and protect information.
              These Terms incorporate the Privacy Policy by reference.
            </p>
          </TermsSection>

          <TermsSection title="10. Limitation of Liability">
            <p>
              ToolNest and its tools are provided &ldquo;as is&rdquo; and
              &ldquo;as available&rdquo; without warranties of any kind, either
              express or implied. To the fullest extent permitted by law,
              ToolNest shall not be liable for any direct, indirect,
              incidental, consequential, or special damages arising from your
              use of, or inability to use, the Site or its tools.
            </p>
          </TermsSection>

          <TermsSection title="11. Service Availability">
            <p>
              We strive to keep ToolNest available but do not guarantee
              uninterrupted or error-free access. We may modify, suspend, or
              discontinue the Site or any tool at any time without notice. We
              are not liable for any loss resulting from such changes.
            </p>
          </TermsSection>

          <TermsSection title="12. Changes to the Website">
            <p>
              We may update, add, or remove tools, features, or content on
              ToolNest at any time. We may also impose limits on use or access
              without notice. Continued use of the Site after any change
              constitutes acceptance of the updated Site.
            </p>
          </TermsSection>

          <TermsSection title="13. Changes to These Terms">
            <p>
              We may revise these Terms from time to time. The most current
              version will always be posted on this page with an updated
              revision date. Your continued use of ToolNest after changes are
              posted constitutes your acceptance of the updated Terms.
            </p>
          </TermsSection>

          <TermsSection title="14. Termination or Restriction of Access">
            <p>
              We may terminate or restrict your access to ToolNest at any
              time, without notice, if we believe you have violated these
              Terms or for any other reason. Upon termination, all provisions
              of these Terms that by their nature should survive termination
              shall remain in effect.
            </p>
          </TermsSection>

          <TermsSection title="15. Contact Information">
            <p>
              If you have questions about these Terms, please reach out
              through our{' '}
              <a
                href="/contact"
                className="text-brand-purple underline underline-offset-2 hover:opacity-80"
              >
                contact page
              </a>
              .
            </p>
          </TermsSection>
        </div>
      </section>
    </>
  );
}

function TermsSection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded-2xl glass-card p-8">
      <h2 className="text-lg font-semibold tracking-tight">{title}</h2>
      <div className="mt-3 space-y-3 text-sm leading-relaxed text-muted-foreground">
        {children}
      </div>
    </div>
  );
}
