import type { AudioToolConfig } from '@/components/audio/audio-tool';

export const audioToolConfigs: Record<string, AudioToolConfig> = {
  'audio-converter': { slug: 'audio-converter', label: 'Audio Converter', description: 'Convert audio', accept: 'audio/mp3,audio/wav,audio/ogg,audio/m4a', supportsMultiple: false, showSpeedControl: false, showVolumeControl: false, showPitchControl: false, showTimeRange: false, showTextInput: false, isRecorder: false, isSpeechToText: false, outputFormat: 'wav', actionLabel: 'Convert Audio' },
  'mp3-cutter': { slug: 'mp3-cutter', label: 'MP3 Cutter', description: 'Cut MP3', accept: 'audio/mp3', supportsMultiple: false, showSpeedControl: false, showVolumeControl: false, showPitchControl: false, showTimeRange: true, showTextInput: false, isRecorder: false, isSpeechToText: false, outputFormat: 'mp3', actionLabel: 'Cut MP3' },
  'audio-trimmer': { slug: 'audio-trimmer', label: 'Audio Trimmer', description: 'Trim audio', accept: 'audio/mp3,audio/wav,audio/ogg', supportsMultiple: false, showSpeedControl: false, showVolumeControl: false, showPitchControl: false, showTimeRange: true, showTextInput: false, isRecorder: false, isSpeechToText: false, outputFormat: 'mp3', actionLabel: 'Trim Audio' },
  'audio-compressor': { slug: 'audio-compressor', label: 'Audio Compressor', description: 'Compress audio', accept: 'audio/mp3,audio/wav,audio/ogg', supportsMultiple: false, showSpeedControl: false, showVolumeControl: false, showPitchControl: false, showTimeRange: false, showTextInput: false, isRecorder: false, isSpeechToText: false, outputFormat: 'mp3', actionLabel: 'Compress Audio' },
  'merge-audio': { slug: 'merge-audio', label: 'Merge Audio', description: 'Merge audio', accept: 'audio/mp3,audio/wav,audio/ogg', supportsMultiple: true, showSpeedControl: false, showVolumeControl: false, showPitchControl: false, showTimeRange: false, showTextInput: false, isRecorder: false, isSpeechToText: false, outputFormat: 'mp3', actionLabel: 'Merge Audio' },
  'reverse-audio': { slug: 'reverse-audio', label: 'Reverse Audio', description: 'Reverse audio', accept: 'audio/mp3,audio/wav,audio/ogg', supportsMultiple: false, showSpeedControl: false, showVolumeControl: false, showPitchControl: false, showTimeRange: false, showTextInput: false, isRecorder: false, isSpeechToText: false, outputFormat: 'mp3', actionLabel: 'Reverse Audio' },
  'volume-booster': { slug: 'volume-booster', label: 'Volume Booster', description: 'Boost volume', accept: 'audio/mp3,audio/wav,audio/ogg', supportsMultiple: false, showSpeedControl: false, showVolumeControl: true, showPitchControl: false, showTimeRange: false, showTextInput: false, isRecorder: false, isSpeechToText: false, outputFormat: 'mp3', actionLabel: 'Boost Volume' },
  'audio-speed-changer': { slug: 'audio-speed-changer', label: 'Audio Speed Changer', description: 'Change speed', accept: 'audio/mp3,audio/wav,audio/ogg', supportsMultiple: false, showSpeedControl: true, showVolumeControl: false, showPitchControl: false, showTimeRange: false, showTextInput: false, isRecorder: false, isSpeechToText: false, outputFormat: 'mp3', actionLabel: 'Change Speed' },
  'pitch-changer': { slug: 'pitch-changer', label: 'Pitch Changer', description: 'Change pitch', accept: 'audio/mp3,audio/wav,audio/ogg', supportsMultiple: false, showSpeedControl: false, showVolumeControl: false, showPitchControl: true, showTimeRange: false, showTextInput: false, isRecorder: false, isSpeechToText: false, outputFormat: 'mp3', actionLabel: 'Change Pitch' },
  'voice-recorder': { slug: 'voice-recorder', label: 'Voice Recorder', description: 'Record audio', accept: 'audio/*', supportsMultiple: false, showSpeedControl: false, showVolumeControl: false, showPitchControl: false, showTimeRange: false, showTextInput: false, isRecorder: true, isSpeechToText: false, outputFormat: 'webm', actionLabel: 'Record' },
  'text-to-speech': { slug: 'text-to-speech', label: 'Text to Speech', description: 'Text to speech', accept: '', supportsMultiple: false, showSpeedControl: true, showVolumeControl: true, showPitchControl: false, showTimeRange: false, showTextInput: true, isRecorder: false, isSpeechToText: false, outputFormat: 'mp3', actionLabel: 'Speak' },
  'speech-to-text': { slug: 'speech-to-text', label: 'Speech to Text', description: 'Speech to text', accept: '', supportsMultiple: false, showSpeedControl: false, showVolumeControl: false, showPitchControl: false, showTimeRange: false, showTextInput: false, isRecorder: false, isSpeechToText: true, outputFormat: 'txt', actionLabel: 'Transcribe' },
  'audio-metadata-viewer': { slug: 'audio-metadata-viewer', label: 'Audio Metadata Viewer', description: 'View metadata', accept: 'audio/mp3,audio/wav,audio/ogg', supportsMultiple: false, showSpeedControl: false, showVolumeControl: false, showPitchControl: false, showTimeRange: false, showTextInput: false, isRecorder: false, isSpeechToText: false, outputFormat: 'txt', actionLabel: 'View Metadata' },
  'audio-metadata-remover': { slug: 'audio-metadata-remover', label: 'Audio Metadata Remover', description: 'Remove metadata', accept: 'audio/mp3,audio/wav,audio/ogg', supportsMultiple: false, showSpeedControl: false, showVolumeControl: false, showPitchControl: false, showTimeRange: false, showTextInput: false, isRecorder: false, isSpeechToText: false, outputFormat: 'mp3', actionLabel: 'Remove Metadata' },
};
