import type { LucideIcon } from 'lucide-react';
import {
  AlignLeft,
  Archive,
  AreaChart,
  ArrowDownUp,
  ArrowLeftRight,
  AtSign,
  AudioLines,
  Award,
  BadgePercent,
  Barcode,
  Binary,
  Blend,
  Bot,
  Box,
  Boxes,
  Braces,
  Briefcase,
  Brush,
  Cake,
  Calculator,
  Calendar,
  CalendarClock,
  CalendarDays,
  Camera,
  CaseSensitive,
  CheckCircle2,
  ClipboardList,
  Clock,
  Code2,
  Coins,
  Contrast,
  Crop,
  Database,
  Dices,
  Droplets,
  Eraser,
  Eye,
  Facebook,
  FileCheck,
  FileCode2,
  FileDiff,
  FileEdit,
  FileImage,
  FileJson,
  FileMinus2,
  FileOutput,
  FilePlus,
  FilePlus2,
  FileSearch,
  FileSignature,
  FileSpreadsheet,
  FileText,
  Film,
  Fingerprint,
  FlipHorizontal2,
  Forward,
  Frame,
  Fuel,
  Gauge,
  Globe,
  HardDrive,
  Hash,
  HeartPulse,
  HelpCircle,
  History as HistoryIcon,
  ImageIcon,
  Info,
  Instagram,
  Key,
  KeyRound,
  Landmark,
  Layers,
  Lightbulb,
  Link,
  Link2,
  Linkedin,
  ListChecks,
  ListOrdered,
  ListTodo,
  ListTree,
  Lock,
  Mail,
  MailOpen,
  MapPin,
  Megaphone,
  Mic,
  Minimize2,
  Monitor,
  MousePointerClick,
  Music,
  Network,
  Package,
  Palette,
  PenLine,
  Percent,
  Pilcrow,
  Pin,
  Pipette,
  Presentation,
  QrCode,
  Receipt,
  RefreshCw,
  Regex,
  Repeat,
  Repeat2,
  Replace,
  Reply,
  Rocket,
  RotateCw,
  Route,
  Ruler,
  Scale,
  Scaling,
  ScanLine,
  Scissors,
  Search,
  Server,
  Share2,
  Shield,
  Image as ImageLucide,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sigma,
  Slash,
  Sparkles,
  SpellCheck,
  Spline,
  Square,
  Stamp,
  Star,
  StickyNote,
  Store,
  Sun,
  Table,
  Tag,
  Tags,
  Thermometer,
  Timer,
  TrendingUp,
  Twitter,
  Type,
  Unlock,
  UserCheck,
  UserPlus,
  Utensils,
  Video,
  Volume2,
  VolumeX,
  Wand2,
  Wind,
  Youtube,
  Zap,
} from 'lucide-react';


export type Category = {
  slug: string;
  name: string;
  count: number;
  icon: LucideIcon;
  gradient: string;
  description: string;
};

export type Tool = {
  slug: string;
  name: string;
  description: string;
  category: string;
  icon: LucideIcon;
  gradient: string;
  badge?: string;
  isNew?: boolean;
  popularity: number;
  addedDaysAgo?: number;
};

export const categories: Category[] = [
  {
    slug: 'pdf-tools',
    name: 'PDF Tools',
    count: 24,
    icon: FileText,
    gradient: 'from-rose-400 to-red-600',
    description: 'Merge, split, convert and optimize PDF files.',
  },
  {
    slug: 'image-tools',
    name: 'Image Tools',
    count: 38,
    icon: ImageIcon,
    gradient: 'from-fuchsia-400 to-purple-600',
    description: 'Compress, resize and convert images instantly.',
  },
  {
    slug: 'qr-tools',
    name: 'QR & Barcode Tools',
    count: 12,
    icon: QrCode,
    gradient: 'from-emerald-400 to-teal-600',
    description: 'Generate QR codes and barcodes for anything.',
  },
  {
    slug: 'seo-tools',
    name: 'SEO Tools',
    count: 21,
    icon: Search,
    gradient: 'from-orange-400 to-amber-600',
    description: 'Analyze and improve your search visibility.',
  },
  {
    slug: 'ai-tools',
    name: 'AI Tools',
    count: 18,
    icon: Sparkles,
    gradient: 'from-sky-400 to-blue-600',
    description: 'Generate text, images and ideas with AI.',
  },
  {
    slug: 'text-tools',
    name: 'Text Tools',
    count: 30,
    icon: Type,
    gradient: 'from-cyan-400 to-blue-500',
    description: 'Count, convert, format and transform text.',
  },
  {
    slug: 'developer-tools',
    name: 'Developer Tools',
    count: 27,
    icon: Code2,
    gradient: 'from-violet-400 to-indigo-600',
    description: 'Format, encode and debug code faster.',
  },
  {
    slug: 'calculators',
    name: 'Calculators',
    count: 19,
    icon: Calculator,
    gradient: 'from-blue-400 to-purple-500',
    description: 'Financial, health and everyday calculators.',
  },
  {
    slug: 'converters',
    name: 'Converters',
    count: 16,
    icon: ArrowLeftRight,
    gradient: 'from-indigo-400 to-blue-600',
    description: 'Convert units, files and formats with ease.',
  },
  {
    slug: 'social-media-tools',
    name: 'Social Media Tools',
    count: 15,
    icon: Share2,
    gradient: 'from-pink-400 to-rose-600',
    description: 'Optimize posts and grow your presence.',
  },
  {
    slug: 'security-tools',
    name: 'Security Tools',
    count: 4,
    icon: ShieldCheck,
    gradient: 'from-cyan-400 to-blue-500',
    description: 'Generate passwords, UUIDs and check password strength.',
  },
  {
    slug: 'video-tools',
    name: 'Video Tools',
    count: 18,
    icon: Video,
    gradient: 'from-red-400 to-rose-600',
    description: 'Compress, convert, trim and edit videos in your browser.',
  },
  {
    slug: 'audio-tools',
    name: 'Audio Tools',
    count: 14,
    icon: AudioLines,
    gradient: 'from-green-400 to-emerald-600',
    description: 'Convert, trim, record and edit audio files instantly.',
  },
  {
    slug: 'office-tools',
    name: 'Office Tools',
    count: 16,
    icon: FileSpreadsheet,
    gradient: 'from-blue-400 to-indigo-600',
    description: 'Convert and edit Word, Excel, PowerPoint and CSV files.',
  },
  {
    slug: 'design-tools',
    name: 'Design Tools',
    count: 14,
    icon: Palette,
    gradient: 'from-fuchsia-400 to-pink-600',
    description: 'Generate palettes, gradients, shadows and CSS styles.',
  },
  {
    slug: 'web-utilities',
    name: 'Web Utilities',
    count: 12,
    icon: Globe,
    gradient: 'from-cyan-400 to-teal-600',
    description: 'Check browsers, DNS, SSL and inspect web resources.',
  },
  {
    slug: 'productivity',
    name: 'Productivity',
    count: 10,
    icon: ListTodo,
    gradient: 'from-amber-400 to-orange-600',
    description: 'Notes, timers, calendars and planning utilities.',
  },
];

export const tools: Tool[] = [
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Create custom QR codes for links, text and more in seconds.',
    category: 'QR & Barcode Tools',
    icon: QrCode,
    gradient: 'from-emerald-400 to-teal-600',
    badge: 'Popular',
    popularity: 98,
  },
  {
    slug: 'barcode-generator',
    name: 'Barcode Generator',
    description: 'Generate barcodes in multiple formats for products and labels.',
    category: 'QR & Barcode Tools',
    icon: Barcode,
    gradient: 'from-emerald-400 to-green-600',
    popularity: 84,
  },
  {
    slug: 'qr-scanner',
    name: 'QR Scanner',
    description: 'Scan QR codes with your camera or decode them from an image.',
    category: 'QR & Barcode Tools',
    icon: ScanLine,
    gradient: 'from-sky-400 to-indigo-600',
    popularity: 88,
  },
  {
    slug: 'qr-history',
    name: 'QR History',
    description: 'View, reopen and download every QR code you generated or scanned.',
    category: 'QR & Barcode Tools',
    icon: HistoryIcon,
    gradient: 'from-slate-400 to-slate-600',
    popularity: 70,
  },
  {
    slug: 'image-compressor',
    name: 'Image Compressor',
    description: 'Reduce image file size without losing visible quality.',
    category: 'Image Tools',
    icon: Gauge,
    gradient: 'from-fuchsia-400 to-purple-600',
    badge: 'Popular',
    popularity: 95,
  },
  {
    slug: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize images to exact dimensions with aspect ratio lock.',
    category: 'Image Tools',
    icon: Scaling,
    gradient: 'from-sky-400 to-blue-600',
    popularity: 86,
  },
  {
    slug: 'image-converter',
    name: 'Image Converter',
    description: 'Convert images between JPG, PNG and WEBP formats.',
    category: 'Image Tools',
    icon: Repeat,
    gradient: 'from-teal-400 to-cyan-600',
    popularity: 82,
  },
  {
    slug: 'image-cropper',
    name: 'Image Cropper',
    description: 'Crop images into square, 16:9, 4:3 or circle shapes.',
    category: 'Image Tools',
    icon: Crop,
    gradient: 'from-amber-400 to-orange-600',
    badge: 'New',
    popularity: 80,
  },
  {
    slug: 'pdf-merge',
    name: 'PDF Merge',
    description: 'Combine multiple PDF files into a single document.',
    category: 'PDF Tools',
    icon: FilePlus,
    gradient: 'from-rose-400 to-red-600',
    badge: 'Popular',
    popularity: 92,
  },
  {
    slug: 'pdf-split',
    name: 'PDF Split',
    description: 'Extract pages or split a PDF into separate files.',
    category: 'PDF Tools',
    icon: Scissors,
    gradient: 'from-rose-400 to-pink-600',
    popularity: 78,
  },
  {
    slug: 'pdf-compress',
    name: 'PDF Compress',
    description: 'Reduce PDF file size with three compression levels.',
    category: 'PDF Tools',
    icon: Archive,
    gradient: 'from-red-400 to-orange-600',
    badge: 'Popular',
    popularity: 89,
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    description: 'Create strong, secure and random passwords instantly.',
    category: 'Security Tools',
    icon: KeyRound,
    gradient: 'from-cyan-400 to-blue-500',
    badge: 'Popular',
    popularity: 90,
  },
  {
    slug: 'password-strength-checker',
    name: 'Password Strength Checker',
    description: 'Analyze password strength and estimate crack time.',
    category: 'Security Tools',
    icon: ShieldCheck,
    gradient: 'from-emerald-400 to-teal-600',
    popularity: 85,
  },
  {
    slug: 'username-generator',
    name: 'Username Generator',
    description: 'Generate unique random usernames with prefixes and suffixes.',
    category: 'Security Tools',
    icon: UserPlus,
    gradient: 'from-violet-400 to-purple-600',
    popularity: 82,
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate random UUID v4 identifiers in bulk.',
    category: 'Security Tools',
    icon: Fingerprint,
    gradient: 'from-blue-400 to-indigo-600',
    popularity: 78,
  },
  {
    slug: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences and reading time.',
    category: 'Text Tools',
    icon: AlignLeft,
    gradient: 'from-sky-400 to-cyan-500',
    popularity: 88,
  },
  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Beautify, minify and validate JSON with syntax highlighting.',
    category: 'Developer Tools',
    icon: Braces,
    gradient: 'from-violet-400 to-indigo-600',
    badge: 'Popular',
    popularity: 93,
  },
  {
    slug: 'base64-encoder',
    name: 'Base64 Encoder',
    description: 'Encode and decode text or files to and from Base64.',
    category: 'Developer Tools',
    icon: Binary,
    gradient: 'from-indigo-400 to-blue-600',
    popularity: 80,
  },
  {
    slug: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate your exact age in years, months and days.',
    category: 'Calculators',
    icon: Cake,
    gradient: 'from-pink-400 to-rose-600',
    badge: 'Popular',
    popularity: 88,
  },
  {
    slug: 'bmi-calculator',
    name: 'BMI Calculator',
    description: 'Calculate Body Mass Index from height and weight.',
    category: 'Calculators',
    icon: HeartPulse,
    gradient: 'from-red-400 to-pink-600',
    popularity: 85,
  },
  {
    slug: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Calculate percentages, increases and decreases instantly.',
    category: 'Calculators',
    icon: Percent,
    gradient: 'from-blue-400 to-cyan-600',
    popularity: 84,
  },
  {
    slug: 'loan-emi-calculator',
    name: 'Loan EMI Calculator',
    description: 'Calculate monthly loan EMI, total interest and payment.',
    category: 'Calculators',
    icon: Landmark,
    gradient: 'from-emerald-400 to-green-600',
    badge: 'Popular',
    popularity: 90,
  },
  {
    slug: 'gst-calculator',
    name: 'GST Calculator',
    description: 'Calculate GST inclusive and exclusive amounts instantly.',
    category: 'Calculators',
    icon: Receipt,
    gradient: 'from-indigo-400 to-blue-600',
    popularity: 82,
  },
  {
    slug: 'discount-calculator',
    name: 'Discount Calculator',
    description: 'Calculate discount amounts and final prices after savings.',
    category: 'Calculators',
    icon: BadgePercent,
    gradient: 'from-amber-400 to-orange-600',
    popularity: 80,
  },
  {
    slug: 'tip-calculator',
    name: 'Tip Calculator',
    description: 'Calculate tips and split bills between any number of people.',
    category: 'Calculators',
    icon: Utensils,
    gradient: 'from-teal-400 to-cyan-600',
    popularity: 78,
  },
  {
    slug: 'simple-interest-calculator',
    name: 'Simple Interest Calculator',
    description: 'Calculate simple interest on loans and investments.',
    category: 'Calculators',
    icon: TrendingUp,
    gradient: 'from-lime-400 to-green-600',
    popularity: 75,
  },
  {
    slug: 'compound-interest-calculator',
    name: 'Compound Interest Calculator',
    description: 'Calculate compound interest with compounding frequency.',
    category: 'Calculators',
    icon: Sigma,
    gradient: 'from-violet-400 to-purple-600',
    popularity: 77,
  },
  {
    slug: 'scientific-calculator',
    name: 'Scientific Calculator',
    description: 'Advanced calculator with trig, log and exponential functions.',
    category: 'Calculators',
    icon: Calculator,
    gradient: 'from-slate-400 to-gray-600',
    badge: 'New',
    popularity: 83,
  },
  {
    slug: 'length-converter',
    name: 'Length Converter',
    description: 'Convert between metres, feet, inches, miles and more.',
    category: 'Converters',
    icon: Ruler,
    gradient: 'from-sky-400 to-blue-600',
    popularity: 82,
  },
  {
    slug: 'weight-converter',
    name: 'Weight Converter',
    description: 'Convert between kilograms, pounds, ounces and tonnes.',
    category: 'Converters',
    icon: Scale,
    gradient: 'from-orange-400 to-amber-600',
    popularity: 80,
  },
  {
    slug: 'temperature-converter',
    name: 'Temperature Converter',
    description: 'Convert between Celsius, Fahrenheit and Kelvin.',
    category: 'Converters',
    icon: Thermometer,
    gradient: 'from-red-400 to-orange-600',
    popularity: 81,
  },
  {
    slug: 'time-converter',
    name: 'Time Converter',
    description: 'Convert between seconds, minutes, hours, days and weeks.',
    category: 'Converters',
    icon: Clock,
    gradient: 'from-indigo-400 to-violet-600',
    popularity: 76,
  },
  {
    slug: 'data-storage-converter',
    name: 'Data Storage Converter',
    description: 'Convert between bytes, KB, MB, GB, TB and PB.',
    category: 'Converters',
    icon: HardDrive,
    gradient: 'from-teal-400 to-emerald-600',
    popularity: 74,
  },
  {
    slug: 'url-encoder',
    name: 'URL Encoder',
    description: 'Encode and decode URLs to safely pass special characters.',
    category: 'Developer Tools',
    icon: Link2,
    gradient: 'from-indigo-400 to-cyan-600',
    popularity: 76,
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions with live match highlighting.',
    category: 'Developer Tools',
    icon: Regex,
    gradient: 'from-violet-400 to-purple-600',
    badge: 'New',
    popularity: 78,
  },
  {
    slug: 'character-counter',
    name: 'Character Counter',
    description: 'Count characters, words and spaces in your text instantly.',
    category: 'Text Tools',
    icon: Hash,
    gradient: 'from-sky-400 to-blue-500',
    popularity: 84,
  },
  {
    slug: 'remove-duplicate-lines',
    name: 'Remove Duplicate Lines',
    description: 'Remove duplicate lines from any text instantly.',
    category: 'Text Tools',
    icon: ListOrdered,
    gradient: 'from-teal-400 to-emerald-600',
    popularity: 72,
  },
  {
    slug: 'text-sorter',
    name: 'Text Sorter',
    description: 'Sort lines alphabetically, reverse or remove empty lines.',
    category: 'Text Tools',
    icon: ListOrdered,
    gradient: 'from-indigo-400 to-violet-600',
    popularity: 70,
  },
  {
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text in words, sentences or paragraphs.',
    category: 'Text Tools',
    icon: Pilcrow,
    gradient: 'from-amber-400 to-yellow-600',
    popularity: 76,
  },
  {
    slug: 'case-converter',
    name: 'Case Converter',
    description: 'Switch text between upper, lower, title, sentence and toggle case.',
    category: 'Text Tools',
    icon: CaseSensitive,
    gradient: 'from-sky-400 to-indigo-500',
    badge: 'New',
    popularity: 80,
  },
  {
    slug: 'json-validator',
    name: 'JSON Validator',
    description: 'Validate JSON and find syntax errors instantly.',
    category: 'Developer Tools',
    icon: CheckCircle2,
    gradient: 'from-green-400 to-emerald-600',
    popularity: 79,
  },
  {
    slug: 'html-formatter',
    name: 'HTML Formatter',
    description: 'Beautify and minify HTML code with proper indentation.',
    category: 'Developer Tools',
    icon: FileCode2,
    gradient: 'from-orange-400 to-red-600',
    popularity: 76,
  },
  {
    slug: 'css-minifier',
    name: 'CSS Minifier',
    description: 'Minify CSS to reduce file size and improve load speed.',
    category: 'Developer Tools',
    icon: Minimize2,
    gradient: 'from-sky-400 to-blue-600',
    popularity: 73,
  },
  {
    slug: 'js-minifier',
    name: 'JavaScript Minifier',
    description: 'Minify JavaScript code to reduce file size instantly.',
    category: 'Developer Tools',
    icon: FileCode2,
    gradient: 'from-yellow-400 to-amber-600',
    popularity: 75,
  },
  {
    slug: 'sha256-hash-generator',
    name: 'SHA256 Hash Generator',
    description: 'Generate SHA-256 hashes from any text input.',
    category: 'Developer Tools',
    icon: Fingerprint,
    gradient: 'from-indigo-400 to-violet-600',
    popularity: 72,
  },
  {
    slug: 'md5-hash-generator',
    name: 'MD5 Hash Generator',
    description: 'Generate MD5 hashes from any text input instantly.',
    category: 'Developer Tools',
    icon: Key,
    gradient: 'from-rose-400 to-pink-600',
    popularity: 70,
  },
  {
    slug: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate SEO meta tags for title, description and more.',
    category: 'SEO Tools',
    icon: Tags,
    gradient: 'from-orange-400 to-amber-600',
    badge: 'Popular',
    popularity: 85,
  },
  {
    slug: 'open-graph-generator',
    name: 'Open Graph Generator',
    description: 'Generate Open Graph tags for social media sharing.',
    category: 'SEO Tools',
    icon: Share2,
    gradient: 'from-blue-400 to-indigo-600',
    popularity: 80,
  },
  {
    slug: 'twitter-card-generator',
    name: 'Twitter Card Generator',
    description: 'Generate Twitter Card meta tags for better link previews.',
    category: 'SEO Tools',
    icon: Twitter,
    gradient: 'from-sky-400 to-blue-600',
    popularity: 78,
  },
  {
    slug: 'robots-txt-generator',
    name: 'Robots.txt Generator',
    description: 'Generate robots.txt files to control search engine crawlers.',
    category: 'SEO Tools',
    icon: Bot,
    gradient: 'from-slate-400 to-gray-600',
    popularity: 76,
  },
  {
    slug: 'sitemap-generator',
    name: 'Sitemap Generator',
    description: 'Generate XML sitemaps for search engine indexing.',
    category: 'SEO Tools',
    icon: Network,
    gradient: 'from-emerald-400 to-teal-600',
    popularity: 77,
  },
  {
    slug: 'keyword-density-checker',
    name: 'Keyword Density Checker',
    description: 'Analyze keyword density and frequency in your content.',
    category: 'SEO Tools',
    icon: FileSearch,
    gradient: 'from-purple-400 to-violet-600',
    popularity: 74,
  },
  {
    slug: 'slug-generator',
    name: 'Slug Generator',
    description: 'Generate SEO-friendly URL slugs from any text.',
    category: 'SEO Tools',
    icon: Slash,
    gradient: 'from-cyan-400 to-blue-600',
    popularity: 73,
  },
  {
    slug: 'canonical-url-generator',
    name: 'Canonical URL Generator',
    description: 'Generate canonical URL tags to avoid duplicate content.',
    category: 'SEO Tools',
    icon: Link,
    gradient: 'from-teal-400 to-cyan-600',
    popularity: 71,
  },
  {
    slug: 'search-snippet-preview',
    name: 'Search Snippet Preview',
    description: 'Preview how your page appears in Google search results.',
    category: 'SEO Tools',
    icon: Search,
    gradient: 'from-indigo-400 to-blue-600',
    badge: 'New',
    popularity: 82,
  },
  {
    slug: 'redirect-checker',
    name: 'Redirect Checker',
    description: 'Check URL redirect chains and HTTP status codes.',
    category: 'SEO Tools',
    icon: Route,
    gradient: 'from-amber-400 to-orange-600',
    popularity: 70,
  },
  {
    slug: 'background-remover',
    name: 'Background Remover',
    description: 'Remove image backgrounds automatically in your browser.',
    category: 'Image Tools',
    icon: Eraser,
    gradient: 'from-fuchsia-400 to-pink-600',
    isNew: true,
    popularity: 91,
  },
  {
    slug: 'image-watermark',
    name: 'Image Watermark',
    description: 'Add text or logo watermarks to protect your images.',
    category: 'Image Tools',
    icon: Droplets,
    gradient: 'from-cyan-400 to-blue-600',
    isNew: true,
    popularity: 76,
  },
  {
    slug: 'image-rotator',
    name: 'Image Rotator',
    description: 'Rotate images by any angle with live preview.',
    category: 'Image Tools',
    icon: RotateCw,
    gradient: 'from-sky-400 to-indigo-500',
    isNew: true,
    popularity: 70,
  },
  {
    slug: 'image-flipper',
    name: 'Image Flipper',
    description: 'Flip images horizontally or vertically instantly.',
    category: 'Image Tools',
    icon: FlipHorizontal2,
    gradient: 'from-teal-400 to-cyan-600',
    isNew: true,
    popularity: 68,
  },
  {
    slug: 'image-color-picker',
    name: 'Image Color Picker',
    description: 'Pick exact colors from any point in an image.',
    category: 'Image Tools',
    icon: Pipette,
    gradient: 'from-violet-400 to-purple-600',
    isNew: true,
    popularity: 72,
  },
  {
    slug: 'image-blur',
    name: 'Image Blur',
    description: 'Apply adjustable blur effects to your images.',
    category: 'Image Tools',
    icon: Droplets,
    gradient: 'from-blue-400 to-violet-600',
    isNew: true,
    popularity: 65,
  },
  {
    slug: 'image-sharpen',
    name: 'Image Sharpen',
    description: 'Sharpen blurry images with adjustable intensity.',
    category: 'Image Tools',
    icon: Contrast,
    gradient: 'from-amber-400 to-orange-600',
    isNew: true,
    popularity: 67,
  },
  {
    slug: 'image-brightness-adjuster',
    name: 'Image Brightness Adjuster',
    description: 'Adjust the brightness of any image with a slider.',
    category: 'Image Tools',
    icon: Sun,
    gradient: 'from-yellow-400 to-amber-600',
    isNew: true,
    popularity: 69,
  },
  {
    slug: 'image-contrast-adjuster',
    name: 'Image Contrast Adjuster',
    description: 'Fine-tune image contrast with live preview.',
    category: 'Image Tools',
    icon: Contrast,
    gradient: 'from-slate-400 to-gray-600',
    isNew: true,
    popularity: 66,
  },
  {
    slug: 'image-grayscale',
    name: 'Image Grayscale',
    description: 'Convert images to grayscale instantly.',
    category: 'Image Tools',
    icon: Contrast,
    gradient: 'from-gray-400 to-slate-600',
    isNew: true,
    popularity: 71,
  },
  {
    slug: 'image-sepia-filter',
    name: 'Image Sepia Filter',
    description: 'Apply a vintage sepia tone to your images.',
    category: 'Image Tools',
    icon: Sun,
    gradient: 'from-amber-400 to-yellow-600',
    isNew: true,
    popularity: 63,
  },
  {
    slug: 'image-border-creator',
    name: 'Image Border Creator',
    description: 'Add custom borders with adjustable width and color.',
    category: 'Image Tools',
    icon: Frame,
    gradient: 'from-rose-400 to-pink-600',
    isNew: true,
    popularity: 64,
  },
  {
    slug: 'image-rounded-corners',
    name: 'Image Rounded Corners',
    description: 'Round the corners of any image with radius control.',
    category: 'Image Tools',
    icon: Frame,
    gradient: 'from-fuchsia-400 to-rose-600',
    isNew: true,
    popularity: 62,
  },
  {
    slug: 'image-metadata-viewer',
    name: 'Image Metadata Viewer',
    description: 'View EXIF and metadata embedded in your images.',
    category: 'Image Tools',
    icon: Info,
    gradient: 'from-cyan-400 to-teal-600',
    isNew: true,
    popularity: 68,
  },
  {
    slug: 'image-metadata-remover',
    name: 'Image Metadata Remover',
    description: 'Strip EXIF and metadata from images for privacy.',
    category: 'Image Tools',
    icon: Eraser,
    gradient: 'from-emerald-400 to-green-600',
    isNew: true,
    popularity: 75,
  },
  {
    slug: 'pdf-rotate',
    name: 'PDF Rotate',
    description: 'Rotate PDF pages 90, 180 or 270 degrees.',
    category: 'PDF Tools',
    icon: RotateCw,
    gradient: 'from-orange-400 to-red-600',
    isNew: true,
    popularity: 80,
  },
  {
    slug: 'pdf-unlock',
    name: 'PDF Unlock',
    description: 'Remove password protection from PDF files.',
    category: 'PDF Tools',
    icon: Unlock,
    gradient: 'from-amber-400 to-orange-600',
    isNew: true,
    popularity: 78,
  },
  {
    slug: 'pdf-protect',
    name: 'PDF Protect',
    description: 'Add password protection to your PDF documents.',
    category: 'PDF Tools',
    icon: Lock,
    gradient: 'from-red-400 to-rose-600',
    isNew: true,
    popularity: 79,
  },
  {
    slug: 'pdf-page-number',
    name: 'PDF Page Number',
    description: 'Add page numbers to PDF documents automatically.',
    category: 'PDF Tools',
    icon: Hash,
    gradient: 'from-rose-400 to-pink-600',
    isNew: true,
    popularity: 72,
  },
  {
    slug: 'pdf-delete-pages',
    name: 'PDF Delete Pages',
    description: 'Remove unwanted pages from PDF files.',
    category: 'PDF Tools',
    icon: Scissors,
    gradient: 'from-red-400 to-orange-600',
    isNew: true,
    popularity: 77,
  },
  {
    slug: 'pdf-extract-pages',
    name: 'PDF Extract Pages',
    description: 'Extract specific pages from a PDF into a new file.',
    category: 'PDF Tools',
    icon: FileOutput,
    gradient: 'from-amber-400 to-yellow-600',
    isNew: true,
    popularity: 76,
  },
  {
    slug: 'pdf-reorder-pages',
    name: 'PDF Reorder Pages',
    description: 'Rearrange PDF pages in any order with drag and drop.',
    category: 'PDF Tools',
    icon: ArrowDownUp,
    gradient: 'from-orange-400 to-amber-600',
    isNew: true,
    popularity: 74,
  },
  {
    slug: 'pdf-watermark',
    name: 'PDF Watermark',
    description: 'Add text watermarks to PDF documents.',
    category: 'PDF Tools',
    icon: Droplets,
    gradient: 'from-rose-400 to-red-600',
    isNew: true,
    popularity: 70,
  },
  {
    slug: 'pdf-metadata-editor',
    name: 'PDF Metadata Editor',
    description: 'Edit title, author, subject and keywords in PDFs.',
    category: 'PDF Tools',
    icon: FileEdit,
    gradient: 'from-amber-400 to-orange-600',
    isNew: true,
    popularity: 68,
  },
  {
    slug: 'pdf-viewer',
    name: 'PDF Viewer',
    description: 'View and read PDF files directly in your browser.',
    category: 'PDF Tools',
    icon: Eye,
    gradient: 'from-yellow-400 to-amber-600',
    isNew: true,
    popularity: 73,
  },
  {
    slug: 'text-repeater',
    name: 'Text Repeater',
    description: 'Repeat any text multiple times with custom separators.',
    category: 'Text Tools',
    icon: Repeat2,
    gradient: 'from-sky-400 to-blue-600',
    isNew: true,
    popularity: 71,
  },
  {
    slug: 'text-reverser',
    name: 'Text Reverser',
    description: 'Reverse text character by character or line by line.',
    category: 'Text Tools',
    icon: ArrowDownUp,
    gradient: 'from-cyan-400 to-teal-600',
    isNew: true,
    popularity: 69,
  },
  {
    slug: 'random-text-generator',
    name: 'Random Text Generator',
    description: 'Generate random words, sentences and paragraphs.',
    category: 'Text Tools',
    icon: Shuffle,
    gradient: 'from-violet-400 to-purple-600',
    isNew: true,
    popularity: 67,
  },
  {
    slug: 'line-counter',
    name: 'Line Counter',
    description: 'Count lines, words and characters in your text.',
    category: 'Text Tools',
    icon: ListTree,
    gradient: 'from-blue-400 to-indigo-600',
    isNew: true,
    popularity: 66,
  },
  {
    slug: 'remove-extra-spaces',
    name: 'Remove Extra Spaces',
    description: 'Clean up multiple spaces, tabs and blank lines.',
    category: 'Text Tools',
    icon: Eraser,
    gradient: 'from-teal-400 to-cyan-600',
    isNew: true,
    popularity: 68,
  },
  {
    slug: 'text-compare',
    name: 'Text Compare',
    description: 'Compare two text blocks and highlight differences.',
    category: 'Text Tools',
    icon: FileDiff,
    gradient: 'from-indigo-400 to-violet-600',
    isNew: true,
    popularity: 74,
  },
  {
    slug: 'find-and-replace',
    name: 'Find & Replace',
    description: 'Find and replace text with regex support.',
    category: 'Text Tools',
    icon: Replace,
    gradient: 'from-purple-400 to-fuchsia-600',
    isNew: true,
    popularity: 72,
  },
  {
    slug: 'text-cleaner',
    name: 'Text Cleaner',
    description: 'Remove formatting, special chars and clean up text.',
    category: 'Text Tools',
    icon: Wand2,
    gradient: 'from-cyan-400 to-sky-600',
    isNew: true,
    popularity: 70,
  },
  {
    slug: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Write Markdown and see live rendered output instantly.',
    category: 'Text Tools',
    icon: Type,
    gradient: 'from-cyan-400 to-blue-500',
    isNew: true,
    popularity: 76,
  },
  {
    slug: 'html-to-text',
    name: 'HTML to Text',
    description: 'Convert HTML markup to clean plain text.',
    category: 'Text Tools',
    icon: FileCode2,
    gradient: 'from-orange-400 to-red-600',
    isNew: true,
    popularity: 68,
  },
  {
    slug: 'password-encryptor',
    name: 'Password Encryptor',
    description: 'Encrypt text with AES-GCM and a password.',
    category: 'Security Tools',
    icon: Lock,
    gradient: 'from-cyan-400 to-blue-600',
    isNew: true,
    popularity: 73,
  },
  {
    slug: 'password-decryptor',
    name: 'Password Decryptor',
    description: 'Decrypt AES-GCM encrypted text with a password.',
    category: 'Security Tools',
    icon: Unlock,
    gradient: 'from-blue-400 to-indigo-600',
    isNew: true,
    popularity: 71,
  },
  {
    slug: 'random-pin-generator',
    name: 'Random PIN Generator',
    description: 'Generate secure random PINs of any length.',
    category: 'Security Tools',
    icon: KeyRound,
    gradient: 'from-teal-400 to-cyan-600',
    isNew: true,
    popularity: 70,
  },
  {
    slug: 'random-number-generator',
    name: 'Random Number Generator',
    description: 'Generate random numbers within a custom range.',
    category: 'Security Tools',
    icon: Dices,
    gradient: 'from-violet-400 to-purple-600',
    isNew: true,
    popularity: 72,
  },
  {
    slug: 'otp-generator',
    name: 'OTP Generator',
    description: 'Generate one-time passwords using TOTP/HOTP.',
    category: 'Security Tools',
    icon: KeyRound,
    gradient: 'from-emerald-400 to-teal-600',
    isNew: true,
    popularity: 75,
  },
  {
    slug: 'hash-compare',
    name: 'Hash Compare',
    description: 'Compare two hashes to check if they match.',
    category: 'Security Tools',
    icon: ShieldAlert,
    gradient: 'from-rose-400 to-red-600',
    isNew: true,
    popularity: 66,
  },
  {
    slug: 'bcrypt-generator',
    name: 'Bcrypt Generator',
    description: 'Generate bcrypt password hashes with adjustable rounds.',
    category: 'Security Tools',
    icon: ShieldCheck,
    gradient: 'from-indigo-400 to-blue-600',
    isNew: true,
    popularity: 74,
  },
  {
    slug: 'sha1-hash-generator',
    name: 'SHA1 Hash Generator',
    description: 'Generate SHA1 hashes from any text input.',
    category: 'Security Tools',
    icon: Hash,
    gradient: 'from-purple-400 to-violet-600',
    isNew: true,
    popularity: 67,
  },
  {
    slug: 'base32-encoder',
    name: 'Base32 Encoder',
    description: 'Encode text to Base32 format instantly.',
    category: 'Security Tools',
    icon: Braces,
    gradient: 'from-cyan-400 to-teal-600',
    isNew: true,
    popularity: 65,
  },
  {
    slug: 'base32-decoder',
    name: 'Base32 Decoder',
    description: 'Decode Base32 encoded text back to plain text.',
    category: 'Security Tools',
    icon: Braces,
    gradient: 'from-teal-400 to-emerald-600',
    isNew: true,
    popularity: 64,
  },
  {
    slug: 'uuid-bulk-generator',
    name: 'UUID Bulk Generator',
    description: 'Generate multiple UUIDs at once with custom count.',
    category: 'Developer Tools',
    icon: Boxes,
    gradient: 'from-violet-400 to-indigo-600',
    isNew: true,
    popularity: 76,
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode JWT tokens and inspect header and payload.',
    category: 'Developer Tools',
    icon: FileJson,
    gradient: 'from-indigo-400 to-purple-600',
    isNew: true,
    popularity: 78,
  },
  {
    slug: 'jwt-encoder',
    name: 'JWT Encoder',
    description: 'Create JWT tokens from header and payload JSON.',
    category: 'Developer Tools',
    icon: FileJson,
    gradient: 'from-purple-400 to-violet-600',
    isNew: true,
    popularity: 72,
  },
  {
    slug: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries instantly.',
    category: 'Developer Tools',
    icon: Database,
    gradient: 'from-blue-400 to-cyan-600',
    isNew: true,
    popularity: 75,
  },
  {
    slug: 'xml-formatter',
    name: 'XML Formatter',
    description: 'Beautify and format XML documents.',
    category: 'Developer Tools',
    icon: FileCode2,
    gradient: 'from-emerald-400 to-teal-600',
    isNew: true,
    popularity: 70,
  },
  {
    slug: 'xml-validator',
    name: 'XML Validator',
    description: 'Validate XML syntax and find errors instantly.',
    category: 'Developer Tools',
    icon: FileCheck,
    gradient: 'from-teal-400 to-cyan-600',
    isNew: true,
    popularity: 68,
  },
  {
    slug: 'csv-to-json',
    name: 'CSV to JSON',
    description: 'Convert CSV data to structured JSON format.',
    category: 'Developer Tools',
    icon: FileSpreadsheet,
    gradient: 'from-green-400 to-emerald-600',
    isNew: true,
    popularity: 74,
  },
  {
    slug: 'json-to-csv',
    name: 'JSON to CSV',
    description: 'Convert JSON data to CSV format instantly.',
    category: 'Developer Tools',
    icon: FileSpreadsheet,
    gradient: 'from-emerald-400 to-green-600',
    isNew: true,
    popularity: 73,
  },
  {
    slug: 'yaml-formatter',
    name: 'YAML Formatter',
    description: 'Format and beautify YAML documents.',
    category: 'Developer Tools',
    icon: Braces,
    gradient: 'from-rose-400 to-pink-600',
    isNew: true,
    popularity: 67,
  },
  {
    slug: 'yaml-validator',
    name: 'YAML Validator',
    description: 'Validate YAML syntax and find errors quickly.',
    category: 'Developer Tools',
    icon: FileCheck,
    gradient: 'from-pink-400 to-rose-600',
    isNew: true,
    popularity: 65,
  },
  {
    slug: 'color-converter',
    name: 'Color Converter',
    description: 'Convert colors between HEX, RGB, HSL and CMYK.',
    category: 'Developer Tools',
    icon: Palette,
    gradient: 'from-fuchsia-400 to-purple-600',
    isNew: true,
    popularity: 72,
  },
  {
    slug: 'hex-to-rgb',
    name: 'HEX to RGB',
    description: 'Convert HEX color codes to RGB values.',
    category: 'Developer Tools',
    icon: Palette,
    gradient: 'from-violet-400 to-fuchsia-600',
    isNew: true,
    popularity: 70,
  },
  {
    slug: 'rgb-to-hex',
    name: 'RGB to HEX',
    description: 'Convert RGB color values to HEX codes.',
    category: 'Developer Tools',
    icon: Palette,
    gradient: 'from-fuchsia-400 to-pink-600',
    isNew: true,
    popularity: 69,
  },
  {
    slug: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert Unix timestamps to human-readable dates.',
    category: 'Developer Tools',
    icon: Timer,
    gradient: 'from-cyan-400 to-blue-600',
    isNew: true,
    popularity: 76,
  },
  {
    slug: 'unix-time-converter',
    name: 'Unix Time Converter',
    description: 'Convert dates to Unix timestamps and back.',
    category: 'Developer Tools',
    icon: Timer,
    gradient: 'from-blue-400 to-indigo-600',
    isNew: true,
    popularity: 73,
  },
  {
    slug: 'hreflang-generator',
    name: 'Hreflang Generator',
    description: 'Generate hreflang tags for international SEO.',
    category: 'SEO Tools',
    icon: Globe,
    gradient: 'from-blue-400 to-cyan-600',
    isNew: true,
    popularity: 72,
  },
  {
    slug: 'schema-markup-generator',
    name: 'Schema Markup Generator',
    description: 'Generate schema.org JSON-LD structured data.',
    category: 'SEO Tools',
    icon: Braces,
    gradient: 'from-violet-400 to-indigo-600',
    isNew: true,
    popularity: 78,
  },
  {
    slug: 'faq-schema-generator',
    name: 'FAQ Schema Generator',
    description: 'Generate FAQ schema markup for rich results.',
    category: 'SEO Tools',
    icon: FileText,
    gradient: 'from-indigo-400 to-blue-600',
    isNew: true,
    popularity: 75,
  },
  {
    slug: 'breadcrumb-schema-generator',
    name: 'Breadcrumb Schema Generator',
    description: 'Generate breadcrumb schema markup for SEO.',
    category: 'SEO Tools',
    icon: ListTree,
    gradient: 'from-teal-400 to-cyan-600',
    isNew: true,
    popularity: 70,
  },
  {
    slug: 'article-schema-generator',
    name: 'Article Schema Generator',
    description: 'Generate article schema markup for blog posts.',
    category: 'SEO Tools',
    icon: FileText,
    gradient: 'from-cyan-400 to-blue-600',
    isNew: true,
    popularity: 71,
  },
  {
    slug: 'product-schema-generator',
    name: 'Product Schema Generator',
    description: 'Generate product schema markup for e-commerce SEO.',
    category: 'SEO Tools',
    icon: Package,
    gradient: 'from-emerald-400 to-teal-600',
    isNew: true,
    popularity: 74,
  },
  {
    slug: 'website-schema-generator',
    name: 'Website Schema Generator',
    description: 'Generate website schema markup for your site.',
    category: 'SEO Tools',
    icon: Globe,
    gradient: 'from-sky-400 to-blue-600',
    isNew: true,
    popularity: 69,
  },
  {
    slug: 'meta-robots-generator',
    name: 'Meta Robots Generator',
    description: 'Generate meta robots tags for crawl control.',
    category: 'SEO Tools',
    icon: Bot,
    gradient: 'from-amber-400 to-orange-600',
    isNew: true,
    popularity: 68,
  },
  {
    slug: 'keyword-extractor',
    name: 'Keyword Extractor',
    description: 'Extract keywords and key phrases from any text.',
    category: 'SEO Tools',
    icon: FileSearch,
    gradient: 'from-purple-400 to-violet-600',
    isNew: true,
    popularity: 73,
  },
  {
    slug: 'serp-pixel-checker',
    name: 'SERP Pixel Checker',
    description: 'Check pixel width of titles and meta descriptions.',
    category: 'SEO Tools',
    icon: Search,
    gradient: 'from-rose-400 to-pink-600',
    isNew: true,
    popularity: 70,
  },
  {
    slug: 'speed-converter',
    name: 'Speed Converter',
    description: 'Convert between m/s, km/h, mph, knots and more.',
    category: 'Converters',
    icon: Wind,
    gradient: 'from-sky-400 to-blue-600',
    isNew: true,
    popularity: 72,
  },
  {
    slug: 'area-converter',
    name: 'Area Converter',
    description: 'Convert between square metres, acres, hectares and more.',
    category: 'Converters',
    icon: AreaChart,
    gradient: 'from-emerald-400 to-teal-600',
    isNew: true,
    popularity: 68,
  },
  {
    slug: 'volume-converter',
    name: 'Volume Converter',
    description: 'Convert between litres, gallons, cups and more.',
    category: 'Converters',
    icon: Box,
    gradient: 'from-cyan-400 to-blue-600',
    isNew: true,
    popularity: 70,
  },
  {
    slug: 'pressure-converter',
    name: 'Pressure Converter',
    description: 'Convert between pascals, bar, psi and atmospheres.',
    category: 'Converters',
    icon: Gauge,
    gradient: 'from-violet-400 to-purple-600',
    isNew: true,
    popularity: 66,
  },
  {
    slug: 'energy-converter',
    name: 'Energy Converter',
    description: 'Convert between joules, calories, kWh and more.',
    category: 'Converters',
    icon: Zap,
    gradient: 'from-amber-400 to-orange-600',
    isNew: true,
    popularity: 67,
  },
  {
    slug: 'power-converter',
    name: 'Power Converter',
    description: 'Convert between watts, horsepower and kilowatts.',
    category: 'Converters',
    icon: Zap,
    gradient: 'from-yellow-400 to-amber-600',
    isNew: true,
    popularity: 65,
  },
  {
    slug: 'fuel-converter',
    name: 'Fuel Converter',
    description: 'Convert between MPG, L/100km and km/L fuel economy.',
    category: 'Converters',
    icon: Fuel,
    gradient: 'from-red-400 to-orange-600',
    isNew: true,
    popularity: 68,
  },
  {
    slug: 'currency-converter',
    name: 'Currency Converter',
    description: 'Convert currencies using your own exchange rates.',
    category: 'Converters',
    icon: Coins,
    gradient: 'from-green-400 to-emerald-600',
    isNew: true,
    popularity: 76,
  },
  {
    slug: 'ai-blog-title-generator',
    name: 'AI Blog Title Generator',
    description: 'Generate catchy blog titles from your topic.',
    category: 'AI Tools',
    icon: PenLine,
    gradient: 'from-violet-400 to-purple-600',
    isNew: true,
    popularity: 82,
  },
  {
    slug: 'ai-blog-outline-generator',
    name: 'AI Blog Outline Generator',
    description: 'Create structured blog post outlines instantly.',
    category: 'AI Tools',
    icon: ListTree,
    gradient: 'from-indigo-400 to-violet-600',
    isNew: true,
    popularity: 79,
  },
  {
    slug: 'ai-article-idea-generator',
    name: 'AI Article Idea Generator',
    description: 'Brainstorm fresh article ideas from any keyword.',
    category: 'AI Tools',
    icon: Lightbulb,
    gradient: 'from-amber-400 to-orange-600',
    isNew: true,
    popularity: 76,
  },
  {
    slug: 'ai-paragraph-generator',
    name: 'AI Paragraph Generator',
    description: 'Generate well-structured paragraphs on any topic.',
    category: 'AI Tools',
    icon: AlignLeft,
    gradient: 'from-sky-400 to-blue-600',
    isNew: true,
    popularity: 80,
  },
  {
    slug: 'ai-sentence-rewriter',
    name: 'AI Sentence Rewriter',
    description: 'Rewrite sentences to improve flow and clarity.',
    category: 'AI Tools',
    icon: RefreshCw,
    gradient: 'from-cyan-400 to-teal-600',
    isNew: true,
    popularity: 78,
  },
  {
    slug: 'ai-grammar-improver',
    name: 'AI Grammar Improver',
    description: 'Fix grammar and spelling errors automatically.',
    category: 'AI Tools',
    icon: SpellCheck,
    gradient: 'from-emerald-400 to-green-600',
    isNew: true,
    popularity: 81,
  },
  {
    slug: 'ai-summarizer',
    name: 'AI Summarizer',
    description: 'Summarize long text into key points instantly.',
    category: 'AI Tools',
    icon: FileMinus2,
    gradient: 'from-rose-400 to-pink-600',
    isNew: true,
    popularity: 84,
  },
  {
    slug: 'ai-expand-text',
    name: 'AI Expand Text',
    description: 'Expand short text into detailed paragraphs.',
    category: 'AI Tools',
    icon: FilePlus2,
    gradient: 'from-blue-400 to-indigo-600',
    isNew: true,
    popularity: 77,
  },
  {
    slug: 'ai-simplify-text',
    name: 'AI Simplify Text',
    description: 'Simplify complex text into easy-to-read language.',
    category: 'AI Tools',
    icon: Minimize2,
    gradient: 'from-teal-400 to-cyan-600',
    isNew: true,
    popularity: 75,
  },
  {
    slug: 'ai-humanize-text',
    name: 'AI Humanize Text',
    description: 'Make AI-generated text sound natural and human.',
    category: 'AI Tools',
    icon: UserCheck,
    gradient: 'from-fuchsia-400 to-pink-600',
    isNew: true,
    popularity: 83,
  },
  {
    slug: 'ai-meta-title-generator',
    name: 'AI Meta Title Generator',
    description: 'Generate SEO-optimized meta titles for pages.',
    category: 'AI Tools',
    icon: Tag,
    gradient: 'from-purple-400 to-violet-600',
    isNew: true,
    popularity: 80,
  },
  {
    slug: 'ai-meta-description-generator',
    name: 'AI Meta Description Generator',
    description: 'Create compelling meta descriptions for SEO.',
    category: 'AI Tools',
    icon: FileText,
    gradient: 'from-indigo-400 to-purple-600',
    isNew: true,
    popularity: 79,
  },
  {
    slug: 'ai-keyword-generator',
    name: 'AI Keyword Generator',
    description: 'Generate targeted keywords for your content.',
    category: 'AI Tools',
    icon: Hash,
    gradient: 'from-violet-400 to-indigo-600',
    isNew: true,
    popularity: 78,
  },
  {
    slug: 'ai-faq-generator',
    name: 'AI FAQ Generator',
    description: 'Generate FAQs with answers from your topic.',
    category: 'AI Tools',
    icon: HelpCircle,
    gradient: 'from-blue-400 to-cyan-600',
    isNew: true,
    popularity: 77,
  },
  {
    slug: 'ai-seo-outline-generator',
    name: 'AI SEO Outline Generator',
    description: 'Create SEO-optimized content outlines instantly.',
    category: 'AI Tools',
    icon: ListTree,
    gradient: 'from-cyan-400 to-blue-600',
    isNew: true,
    popularity: 74,
  },
  {
    slug: 'ai-slug-generator-pro',
    name: 'AI Slug Generator Pro',
    description: 'Generate clean, SEO-friendly URL slugs.',
    category: 'AI Tools',
    icon: Link2,
    gradient: 'from-teal-400 to-emerald-600',
    isNew: true,
    popularity: 72,
  },
  {
    slug: 'ai-product-schema-writer',
    name: 'AI Product Schema Writer',
    description: 'Generate product schema markup automatically.',
    category: 'AI Tools',
    icon: ShoppingCart,
    gradient: 'from-green-400 to-teal-600',
    isNew: true,
    popularity: 70,
  },
  {
    slug: 'ai-alt-text-generator',
    name: 'AI Alt Text Generator',
    description: 'Generate descriptive alt text for images.',
    category: 'AI Tools',
    icon: ImageIcon,
    gradient: 'from-amber-400 to-yellow-600',
    isNew: true,
    popularity: 73,
  },
  {
    slug: 'ai-instagram-caption-generator',
    name: 'AI Instagram Caption Generator',
    description: 'Generate engaging Instagram captions instantly.',
    category: 'AI Tools',
    icon: Instagram,
    gradient: 'from-fuchsia-400 to-pink-600',
    isNew: true,
    popularity: 82,
  },
  {
    slug: 'ai-facebook-caption-generator',
    name: 'AI Facebook Caption Generator',
    description: 'Create engaging Facebook post captions.',
    category: 'AI Tools',
    icon: Facebook,
    gradient: 'from-blue-400 to-indigo-600',
    isNew: true,
    popularity: 76,
  },
  {
    slug: 'ai-linkedin-post-generator',
    name: 'AI LinkedIn Post Generator',
    description: 'Generate professional LinkedIn posts in seconds.',
    category: 'AI Tools',
    icon: Linkedin,
    gradient: 'from-sky-400 to-blue-600',
    isNew: true,
    popularity: 78,
  },
  {
    slug: 'ai-tweet-generator',
    name: 'AI Tweet Generator',
    description: 'Generate catchy tweets that drive engagement.',
    category: 'AI Tools',
    icon: AtSign,
    gradient: 'from-cyan-400 to-sky-600',
    isNew: true,
    popularity: 80,
  },
  {
    slug: 'ai-pinterest-pin-title-generator',
    name: 'AI Pinterest Pin Title Generator',
    description: 'Generate click-worthy Pinterest pin titles.',
    category: 'AI Tools',
    icon: Pin,
    gradient: 'from-red-400 to-rose-600',
    isNew: true,
    popularity: 71,
  },
  {
    slug: 'ai-pinterest-description-generator',
    name: 'AI Pinterest Description Generator',
    description: 'Create SEO-optimized Pinterest descriptions.',
    category: 'AI Tools',
    icon: Pin,
    gradient: 'from-rose-400 to-pink-600',
    isNew: true,
    popularity: 70,
  },
  {
    slug: 'ai-hashtag-generator',
    name: 'AI Hashtag Generator',
    description: 'Generate trending hashtags for any topic.',
    category: 'AI Tools',
    icon: Hash,
    gradient: 'from-violet-400 to-purple-600',
    isNew: true,
    popularity: 79,
  },
  {
    slug: 'ai-social-bio-generator',
    name: 'AI Social Bio Generator',
    description: 'Generate catchy bios for social media profiles.',
    category: 'AI Tools',
    icon: AtSign,
    gradient: 'from-fuchsia-400 to-violet-600',
    isNew: true,
    popularity: 74,
  },
  {
    slug: 'ai-youtube-title-generator',
    name: 'AI YouTube Title Generator',
    description: 'Generate clickable YouTube video titles.',
    category: 'AI Tools',
    icon: Youtube,
    gradient: 'from-red-400 to-orange-600',
    isNew: true,
    popularity: 83,
  },
  {
    slug: 'ai-youtube-description-generator',
    name: 'AI YouTube Description Generator',
    description: 'Create SEO-optimized YouTube descriptions.',
    category: 'AI Tools',
    icon: Youtube,
    gradient: 'from-rose-400 to-red-600',
    isNew: true,
    popularity: 80,
  },
  {
    slug: 'ai-video-hook-generator',
    name: 'AI Video Hook Generator',
    description: 'Generate attention-grabbing video hooks.',
    category: 'AI Tools',
    icon: Youtube,
    gradient: 'from-orange-400 to-red-600',
    isNew: true,
    popularity: 77,
  },
  {
    slug: 'ai-video-script-generator',
    name: 'AI Video Script Generator',
    description: 'Generate complete video scripts from your topic.',
    category: 'AI Tools',
    icon: FileSignature,
    gradient: 'from-amber-400 to-orange-600',
    isNew: true,
    popularity: 76,
  },
  {
    slug: 'ai-shorts-caption-generator',
    name: 'AI Shorts Caption Generator',
    description: 'Generate captions for YouTube Shorts and Reels.',
    category: 'AI Tools',
    icon: Youtube,
    gradient: 'from-pink-400 to-rose-600',
    isNew: true,
    popularity: 75,
  },
  {
    slug: 'ai-thumbnail-text-generator',
    name: 'AI Thumbnail Text Generator',
    description: 'Generate punchy text overlays for thumbnails.',
    category: 'AI Tools',
    icon: Type,
    gradient: 'from-yellow-400 to-amber-600',
    isNew: true,
    popularity: 72,
  },
  {
    slug: 'ai-business-name-generator',
    name: 'AI Business Name Generator',
    description: 'Generate creative business name ideas.',
    category: 'AI Tools',
    icon: Briefcase,
    gradient: 'from-blue-400 to-cyan-600',
    isNew: true,
    popularity: 81,
  },
  {
    slug: 'ai-startup-name-generator',
    name: 'AI Startup Name Generator',
    description: 'Generate catchy startup name ideas.',
    category: 'AI Tools',
    icon: Rocket,
    gradient: 'from-violet-400 to-indigo-600',
    isNew: true,
    popularity: 78,
  },
  {
    slug: 'ai-brand-name-generator',
    name: 'AI Brand Name Generator',
    description: 'Generate memorable brand name ideas.',
    category: 'AI Tools',
    icon: Award,
    gradient: 'from-fuchsia-400 to-purple-600',
    isNew: true,
    popularity: 79,
  },
  {
    slug: 'ai-slogan-generator',
    name: 'AI Slogan Generator',
    description: 'Generate catchy slogans for your brand.',
    category: 'AI Tools',
    icon: Megaphone,
    gradient: 'from-emerald-400 to-teal-600',
    isNew: true,
    popularity: 76,
  },
  {
    slug: 'ai-tagline-generator',
    name: 'AI Tagline Generator',
    description: 'Generate memorable taglines for your business.',
    category: 'AI Tools',
    icon: Megaphone,
    gradient: 'from-teal-400 to-cyan-600',
    isNew: true,
    popularity: 74,
  },
  {
    slug: 'ai-product-description-generator',
    name: 'AI Product Description Generator',
    description: 'Generate compelling product descriptions.',
    category: 'AI Tools',
    icon: ShoppingCart,
    gradient: 'from-green-400 to-emerald-600',
    isNew: true,
    popularity: 80,
  },
  {
    slug: 'ai-marketing-copy-generator',
    name: 'AI Marketing Copy Generator',
    description: 'Generate persuasive marketing copy instantly.',
    category: 'AI Tools',
    icon: Megaphone,
    gradient: 'from-orange-400 to-red-600',
    isNew: true,
    popularity: 78,
  },
  {
    slug: 'ai-email-writer',
    name: 'AI Email Writer',
    description: 'Generate professional emails from your prompt.',
    category: 'AI Tools',
    icon: Mail,
    gradient: 'from-blue-400 to-indigo-600',
    isNew: true,
    popularity: 79,
  },
  {
    slug: 'ai-cold-email-generator',
    name: 'AI Cold Email Generator',
    description: 'Generate cold outreach emails that get replies.',
    category: 'AI Tools',
    icon: MailOpen,
    gradient: 'from-cyan-400 to-blue-600',
    isNew: true,
    popularity: 76,
  },
  {
    slug: 'ai-follow-up-email-generator',
    name: 'AI Follow-up Email Generator',
    description: 'Generate follow-up emails that drive responses.',
    category: 'AI Tools',
    icon: Forward,
    gradient: 'from-indigo-400 to-violet-600',
    isNew: true,
    popularity: 73,
  },
  {
    slug: 'ai-professional-reply-generator',
    name: 'AI Professional Reply Generator',
    description: 'Generate professional email replies instantly.',
    category: 'AI Tools',
    icon: Reply,
    gradient: 'from-purple-400 to-indigo-600',
    isNew: true,
    popularity: 75,
  },
  {
    slug: 'ai-resume-summary-generator',
    name: 'AI Resume Summary Generator',
    description: 'Generate compelling resume summaries.',
    category: 'AI Tools',
    icon: FileText,
    gradient: 'from-sky-400 to-cyan-600',
    isNew: true,
    popularity: 78,
  },
  {
    slug: 'ai-cover-letter-generator',
    name: 'AI Cover Letter Generator',
    description: 'Generate professional cover letters instantly.',
    category: 'AI Tools',
    icon: FileSignature,
    gradient: 'from-teal-400 to-emerald-600',
    isNew: true,
    popularity: 77,
  },
  {
    slug: 'ai-job-description-generator',
    name: 'AI Job Description Generator',
    description: 'Generate detailed job descriptions for any role.',
    category: 'AI Tools',
    icon: ClipboardList,
    gradient: 'from-blue-400 to-violet-600',
    isNew: true,
    popularity: 74,
  },
  {
    slug: 'ai-interview-questions-generator',
    name: 'AI Interview Questions Generator',
    description: 'Generate interview questions for any role.',
    category: 'AI Tools',
    icon: ListChecks,
    gradient: 'from-indigo-400 to-blue-600',
    isNew: true,
    popularity: 76,
  },
  {
    slug: 'ai-amazon-listing-generator',
    name: 'AI Amazon Listing Generator',
    description: 'Generate optimized Amazon product listings.',
    category: 'AI Tools',
    icon: ShoppingBag,
    gradient: 'from-amber-400 to-orange-600',
    isNew: true,
    popularity: 77,
  },
  {
    slug: 'ai-shopify-product-description-generator',
    name: 'AI Shopify Product Description Generator',
    description: 'Generate product descriptions for Shopify stores.',
    category: 'AI Tools',
    icon: Store,
    gradient: 'from-green-400 to-teal-600',
    isNew: true,
    popularity: 75,
  },
  {
    slug: 'ai-etsy-product-description-generator',
    name: 'AI Etsy Product Description Generator',
    description: 'Generate product descriptions for Etsy shops.',
    category: 'AI Tools',
    icon: Store,
    gradient: 'from-rose-400 to-orange-600',
    isNew: true,
    popularity: 73,
  },
  {
    slug: 'ai-ebay-listing-generator',
    name: 'AI eBay Listing Generator',
    description: 'Generate optimized eBay product listings.',
    category: 'AI Tools',
    icon: ShoppingCart,
    gradient: 'from-blue-400 to-cyan-600',
    isNew: true,
    popularity: 71,
  },
  {
    slug: 'video-compressor',
    name: 'Video Compressor',
    description: 'Reduce video file size without losing visible quality.',
    category: 'Video Tools',
    icon: Video,
    gradient: 'from-red-400 to-rose-600',
    isNew: true,
    popularity: 82,
  },
  {
    slug: 'video-converter',
    name: 'Video Converter',
    description: 'Convert videos between MP4, WebM, AVI and more formats.',
    category: 'Video Tools',
    icon: Repeat,
    gradient: 'from-rose-400 to-pink-600',
    isNew: true,
    popularity: 78,
  },
  {
    slug: 'video-trimmer',
    name: 'Video Trimmer',
    description: 'Trim and cut video to keep only the parts you need.',
    category: 'Video Tools',
    icon: Scissors,
    gradient: 'from-orange-400 to-red-600',
    isNew: true,
    popularity: 80,
  },
  {
    slug: 'video-cutter',
    name: 'Video Cutter',
    description: 'Cut out unwanted sections from any video file.',
    category: 'Video Tools',
    icon: Scissors,
    gradient: 'from-amber-400 to-orange-600',
    isNew: true,
    popularity: 76,
  },
  {
    slug: 'video-merger',
    name: 'Video Merger',
    description: 'Combine multiple video clips into one file.',
    category: 'Video Tools',
    icon: FilePlus,
    gradient: 'from-red-400 to-rose-600',
    isNew: true,
    popularity: 77,
  },
  {
    slug: 'video-splitter',
    name: 'Video Splitter',
    description: 'Split a video into multiple equal or custom segments.',
    category: 'Video Tools',
    icon: Scissors,
    gradient: 'from-rose-400 to-red-600',
    isNew: true,
    popularity: 74,
  },
  {
    slug: 'video-rotator',
    name: 'Video Rotator',
    description: 'Rotate videos 90, 180 or 270 degrees instantly.',
    category: 'Video Tools',
    icon: RotateCw,
    gradient: 'from-orange-400 to-amber-600',
    isNew: true,
    popularity: 72,
  },
  {
    slug: 'video-cropper',
    name: 'Video Cropper',
    description: 'Crop video frames to any aspect ratio or dimension.',
    category: 'Video Tools',
    icon: Crop,
    gradient: 'from-red-400 to-orange-600',
    isNew: true,
    popularity: 70,
  },
  {
    slug: 'video-speed-controller',
    name: 'Video Speed Controller',
    description: 'Speed up or slow down video playback speed.',
    category: 'Video Tools',
    icon: Gauge,
    gradient: 'from-amber-400 to-red-600',
    isNew: true,
    popularity: 75,
  },
  {
    slug: 'reverse-video',
    name: 'Reverse Video',
    description: 'Play any video in reverse for creative effects.',
    category: 'Video Tools',
    icon: Repeat,
    gradient: 'from-rose-400 to-orange-600',
    isNew: true,
    popularity: 68,
  },
  {
    slug: 'mute-video',
    name: 'Mute Video',
    description: 'Remove audio from any video file instantly.',
    category: 'Video Tools',
    icon: VolumeX,
    gradient: 'from-red-400 to-rose-600',
    isNew: true,
    popularity: 73,
  },
  {
    slug: 'extract-audio',
    name: 'Extract Audio',
    description: 'Pull the audio track out of any video file.',
    category: 'Video Tools',
    icon: Volume2,
    gradient: 'from-orange-400 to-red-600',
    isNew: true,
    popularity: 76,
  },
  {
    slug: 'video-to-gif',
    name: 'Video to GIF',
    description: 'Convert any video clip into an animated GIF.',
    category: 'Video Tools',
    icon: Film,
    gradient: 'from-rose-400 to-pink-600',
    isNew: true,
    popularity: 79,
  },
  {
    slug: 'gif-to-video',
    name: 'GIF to Video',
    description: 'Convert animated GIFs to MP4 or WebM video.',
    category: 'Video Tools',
    icon: Video,
    gradient: 'from-red-400 to-rose-600',
    isNew: true,
    popularity: 71,
  },
  {
    slug: 'video-watermark',
    name: 'Video Watermark',
    description: 'Add text or image watermarks to your videos.',
    category: 'Video Tools',
    icon: Stamp,
    gradient: 'from-orange-400 to-rose-600',
    isNew: true,
    popularity: 67,
  },
  {
    slug: 'video-thumbnail-generator',
    name: 'Video Thumbnail Generator',
    description: 'Extract frames from videos as thumbnail images.',
    category: 'Video Tools',
    icon: FileImage,
    gradient: 'from-red-400 to-amber-600',
    isNew: true,
    popularity: 69,
  },
  {
    slug: 'video-metadata-viewer',
    name: 'Video Metadata Viewer',
    description: 'Inspect codec, resolution, duration and more.',
    category: 'Video Tools',
    icon: Info,
    gradient: 'from-rose-400 to-red-600',
    isNew: true,
    popularity: 65,
  },
  {
    slug: 'video-metadata-remover',
    name: 'Video Metadata Remover',
    description: 'Strip metadata from video files for privacy.',
    category: 'Video Tools',
    icon: Eraser,
    gradient: 'from-red-400 to-orange-600',
    isNew: true,
    popularity: 63,
  },
  {
    slug: 'audio-converter',
    name: 'Audio Converter',
    description: 'Convert audio between MP3, WAV, OGG and more.',
    category: 'Audio Tools',
    icon: AudioLines,
    gradient: 'from-green-400 to-emerald-600',
    isNew: true,
    popularity: 80,
  },
  {
    slug: 'mp3-cutter',
    name: 'MP3 Cutter',
    description: 'Cut MP3 files to keep only the parts you need.',
    category: 'Audio Tools',
    icon: Scissors,
    gradient: 'from-emerald-400 to-teal-600',
    isNew: true,
    popularity: 82,
  },
  {
    slug: 'audio-trimmer',
    name: 'Audio Trimmer',
    description: 'Trim silence and unwanted parts from audio files.',
    category: 'Audio Tools',
    icon: Scissors,
    gradient: 'from-teal-400 to-cyan-600',
    isNew: true,
    popularity: 75,
  },
  {
    slug: 'audio-compressor',
    name: 'Audio Compressor',
    description: 'Reduce audio file size without losing quality.',
    category: 'Audio Tools',
    icon: Archive,
    gradient: 'from-green-400 to-teal-600',
    isNew: true,
    popularity: 73,
  },
  {
    slug: 'merge-audio',
    name: 'Merge Audio',
    description: 'Combine multiple audio files into one track.',
    category: 'Audio Tools',
    icon: FilePlus,
    gradient: 'from-emerald-400 to-green-600',
    isNew: true,
    popularity: 70,
  },
  {
    slug: 'reverse-audio',
    name: 'Reverse Audio',
    description: 'Play any audio file in reverse instantly.',
    category: 'Audio Tools',
    icon: Repeat,
    gradient: 'from-teal-400 to-emerald-600',
    isNew: true,
    popularity: 66,
  },
  {
    slug: 'volume-booster',
    name: 'Volume Booster',
    description: 'Increase audio volume up to 3x without distortion.',
    category: 'Audio Tools',
    icon: Volume2,
    gradient: 'from-green-400 to-lime-600',
    isNew: true,
    popularity: 78,
  },
  {
    slug: 'audio-speed-changer',
    name: 'Audio Speed Changer',
    description: 'Change audio playback speed without changing pitch.',
    category: 'Audio Tools',
    icon: Gauge,
    gradient: 'from-emerald-400 to-cyan-600',
    isNew: true,
    popularity: 72,
  },
  {
    slug: 'pitch-changer',
    name: 'Pitch Changer',
    description: 'Shift the pitch of any audio file up or down.',
    category: 'Audio Tools',
    icon: Music,
    gradient: 'from-green-400 to-emerald-600',
    isNew: true,
    popularity: 68,
  },
  {
    slug: 'voice-recorder',
    name: 'Voice Recorder',
    description: 'Record audio from your microphone in the browser.',
    category: 'Audio Tools',
    icon: Mic,
    gradient: 'from-teal-400 to-green-600',
    isNew: true,
    popularity: 81,
  },
  {
    slug: 'text-to-speech',
    name: 'Text to Speech',
    description: 'Convert written text into natural-sounding speech.',
    category: 'Audio Tools',
    icon: AudioLines,
    gradient: 'from-emerald-400 to-teal-600',
    isNew: true,
    popularity: 84,
  },
  {
    slug: 'speech-to-text',
    name: 'Speech to Text',
    description: 'Transcribe spoken audio into text using your browser.',
    category: 'Audio Tools',
    icon: Mic,
    gradient: 'from-green-400 to-cyan-600',
    isNew: true,
    popularity: 79,
  },
  {
    slug: 'audio-metadata-viewer',
    name: 'Audio Metadata Viewer',
    description: 'View ID3 tags, bitrate and codec info.',
    category: 'Audio Tools',
    icon: Info,
    gradient: 'from-teal-400 to-emerald-600',
    isNew: true,
    popularity: 64,
  },
  {
    slug: 'audio-metadata-remover',
    name: 'Audio Metadata Remover',
    description: 'Remove ID3 tags and metadata from audio files.',
    category: 'Audio Tools',
    icon: Eraser,
    gradient: 'from-green-400 to-teal-600',
    isNew: true,
    popularity: 62,
  },
  {
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert DOCX documents to PDF in your browser.',
    category: 'Office Tools',
    icon: FileText,
    gradient: 'from-blue-400 to-indigo-600',
    isNew: true,
    popularity: 86,
  },
  {
    slug: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert XLSX spreadsheets to PDF format.',
    category: 'Office Tools',
    icon: FileSpreadsheet,
    gradient: 'from-green-400 to-blue-600',
    isNew: true,
    popularity: 80,
  },
  {
    slug: 'powerpoint-to-pdf',
    name: 'PowerPoint to PDF',
    description: 'Convert PPTX presentations to PDF.',
    category: 'Office Tools',
    icon: Presentation,
    gradient: 'from-orange-400 to-red-600',
    isNew: true,
    popularity: 76,
  },
  {
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF documents to editable DOCX files.',
    category: 'Office Tools',
    icon: FileText,
    gradient: 'from-indigo-400 to-blue-600',
    isNew: true,
    popularity: 84,
  },
  {
    slug: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Extract tables from PDF into XLSX format.',
    category: 'Office Tools',
    icon: FileSpreadsheet,
    gradient: 'from-blue-400 to-green-600',
    isNew: true,
    popularity: 78,
  },
  {
    slug: 'pdf-to-powerpoint',
    name: 'PDF to PowerPoint',
    description: 'Convert PDF pages to editable PPTX slides.',
    category: 'Office Tools',
    icon: Presentation,
    gradient: 'from-red-400 to-orange-600',
    isNew: true,
    popularity: 72,
  },
  {
    slug: 'docx-viewer',
    name: 'DOCX Viewer',
    description: 'View Word documents directly in your browser.',
    category: 'Office Tools',
    icon: FileText,
    gradient: 'from-blue-400 to-cyan-600',
    isNew: true,
    popularity: 74,
  },
  {
    slug: 'docx-editor',
    name: 'DOCX Editor',
    description: 'Edit Word documents online without any software.',
    category: 'Office Tools',
    icon: FileEdit,
    gradient: 'from-indigo-400 to-violet-600',
    isNew: true,
    popularity: 77,
  },
  {
    slug: 'excel-viewer',
    name: 'Excel Viewer',
    description: 'View XLSX spreadsheets in your browser.',
    category: 'Office Tools',
    icon: FileSpreadsheet,
    gradient: 'from-green-400 to-emerald-600',
    isNew: true,
    popularity: 73,
  },
  {
    slug: 'csv-viewer',
    name: 'CSV Viewer',
    description: 'View CSV files in a clean, sortable table.',
    category: 'Office Tools',
    icon: Table,
    gradient: 'from-teal-400 to-cyan-600',
    isNew: true,
    popularity: 76,
  },
  {
    slug: 'csv-editor',
    name: 'CSV Editor',
    description: 'Edit CSV data in a spreadsheet-like interface.',
    category: 'Office Tools',
    icon: Table,
    gradient: 'from-cyan-400 to-blue-600',
    isNew: true,
    popularity: 75,
  },
  {
    slug: 'csv-merge',
    name: 'CSV Merge',
    description: 'Combine multiple CSV files into one dataset.',
    category: 'Office Tools',
    icon: FilePlus,
    gradient: 'from-blue-400 to-teal-600',
    isNew: true,
    popularity: 70,
  },
  {
    slug: 'csv-split',
    name: 'CSV Split',
    description: 'Split a large CSV into multiple smaller files.',
    category: 'Office Tools',
    icon: Scissors,
    gradient: 'from-teal-400 to-blue-600',
    isNew: true,
    popularity: 68,
  },
  {
    slug: 'excel-to-csv',
    name: 'Excel to CSV',
    description: 'Convert XLSX spreadsheets to CSV format.',
    category: 'Office Tools',
    icon: FileSpreadsheet,
    gradient: 'from-green-400 to-teal-600',
    isNew: true,
    popularity: 74,
  },
  {
    slug: 'csv-to-excel',
    name: 'CSV to Excel',
    description: 'Convert CSV data into XLSX spreadsheet files.',
    category: 'Office Tools',
    icon: FileSpreadsheet,
    gradient: 'from-teal-400 to-green-600',
    isNew: true,
    popularity: 72,
  },
  {
    slug: 'ppt-viewer',
    name: 'PPT Viewer',
    description: 'View PowerPoint presentations in your browser.',
    category: 'Office Tools',
    icon: Presentation,
    gradient: 'from-orange-400 to-amber-600',
    isNew: true,
    popularity: 66,
  },
  {
    slug: 'color-palette-generator',
    name: 'Color Palette Generator',
    description: 'Generate beautiful color palettes from any base color.',
    category: 'Design Tools',
    icon: Palette,
    gradient: 'from-fuchsia-400 to-pink-600',
    isNew: true,
    popularity: 85,
  },
  {
    slug: 'gradient-generator',
    name: 'Gradient Generator',
    description: 'Create smooth CSS gradients with live preview.',
    category: 'Design Tools',
    icon: Blend,
    gradient: 'from-violet-400 to-purple-600',
    isNew: true,
    popularity: 82,
  },
  {
    slug: 'css-gradient-generator',
    name: 'CSS Gradient Generator',
    description: 'Generate CSS linear and radial gradient code.',
    category: 'Design Tools',
    icon: Brush,
    gradient: 'from-purple-400 to-indigo-600',
    isNew: true,
    popularity: 79,
  },
  {
    slug: 'glassmorphism-generator',
    name: 'Glassmorphism Generator',
    description: 'Create frosted glass UI effects with CSS.',
    category: 'Design Tools',
    icon: Layers,
    gradient: 'from-cyan-400 to-blue-600',
    isNew: true,
    popularity: 76,
  },
  {
    slug: 'neumorphism-generator',
    name: 'Neumorphism Generator',
    description: 'Generate soft UI neumorphism CSS styles.',
    category: 'Design Tools',
    icon: Box,
    gradient: 'from-slate-400 to-gray-600',
    isNew: true,
    popularity: 73,
  },
  {
    slug: 'css-button-generator',
    name: 'CSS Button Generator',
    description: 'Design and generate CSS buttons with live preview.',
    category: 'Design Tools',
    icon: MousePointerClick,
    gradient: 'from-amber-400 to-orange-600',
    isNew: true,
    popularity: 81,
  },
  {
    slug: 'css-shadow-generator',
    name: 'CSS Shadow Generator',
    description: 'Create box-shadow CSS code with visual preview.',
    category: 'Design Tools',
    icon: Square,
    gradient: 'from-indigo-400 to-violet-600',
    isNew: true,
    popularity: 78,
  },
  {
    slug: 'border-radius-generator',
    name: 'Border Radius Generator',
    description: 'Generate border-radius CSS with visual preview.',
    category: 'Design Tools',
    icon: Spline,
    gradient: 'from-teal-400 to-cyan-600',
    isNew: true,
    popularity: 70,
  },
  {
    slug: 'svg-viewer',
    name: 'SVG Viewer',
    description: 'View and inspect SVG files with code preview.',
    category: 'Design Tools',
    icon: FileCode2,
    gradient: 'from-violet-400 to-purple-600',
    isNew: true,
    popularity: 72,
  },
  {
    slug: 'svg-optimizer',
    name: 'SVG Optimizer',
    description: 'Minify and optimize SVG files for the web.',
    category: 'Design Tools',
    icon: Minimize2,
    gradient: 'from-purple-400 to-indigo-600',
    isNew: true,
    popularity: 69,
  },
  {
    slug: 'svg-to-png',
    name: 'SVG to PNG',
    description: 'Convert SVG files to PNG images instantly.',
    category: 'Design Tools',
    icon: FileImage,
    gradient: 'from-fuchsia-400 to-violet-600',
    isNew: true,
    popularity: 75,
  },
  {
    slug: 'png-to-svg',
    name: 'PNG to SVG',
    description: 'Convert PNG images to SVG vector format.',
    category: 'Design Tools',
    icon: FileImage,
    gradient: 'from-violet-400 to-fuchsia-600',
    isNew: true,
    popularity: 67,
  },
  {
    slug: 'favicon-generator',
    name: 'Favicon Generator',
    description: 'Create favicons from any image for your website.',
    category: 'Design Tools',
    icon: Star,
    gradient: 'from-amber-400 to-yellow-600',
    isNew: true,
    popularity: 77,
  },
  {
    slug: 'image-placeholder-generator',
    name: 'Image Placeholder Generator',
    description: 'Generate placeholder images for mockups and prototypes.',
    category: 'Design Tools',
    icon: ImageIcon,
    gradient: 'from-pink-400 to-rose-600',
    isNew: true,
    popularity: 71,
  },
  {
    slug: 'browser-information',
    name: 'Browser Information',
    description: 'View your browser, OS, screen and capability details.',
    category: 'Web Utilities',
    icon: Monitor,
    gradient: 'from-cyan-400 to-teal-600',
    isNew: true,
    popularity: 72,
  },
  {
    slug: 'user-agent-parser',
    name: 'User Agent Parser',
    description: 'Parse and decode any user agent string.',
    category: 'Web Utilities',
    icon: Info,
    gradient: 'from-teal-400 to-cyan-600',
    isNew: true,
    popularity: 68,
  },
  {
    slug: 'ip-address-checker',
    name: 'IP Address Checker',
    description: 'Check your IP address and network details.',
    category: 'Web Utilities',
    icon: Server,
    gradient: 'from-blue-400 to-cyan-600',
    isNew: true,
    popularity: 75,
  },
  {
    slug: 'http-header-viewer',
    name: 'HTTP Header Viewer',
    description: 'View HTTP response headers for any URL.',
    category: 'Web Utilities',
    icon: FileSearch,
    gradient: 'from-cyan-400 to-blue-600',
    isNew: true,
    popularity: 66,
  },
  {
    slug: 'cookie-viewer',
    name: 'Cookie Viewer',
    description: 'Inspect cookies stored by your browser.',
    category: 'Web Utilities',
    icon: Eye,
    gradient: 'from-teal-400 to-emerald-600',
    isNew: true,
    popularity: 63,
  },
  {
    slug: 'dns-lookup',
    name: 'DNS Lookup',
    description: 'Look up DNS records for any domain.',
    category: 'Web Utilities',
    icon: Network,
    gradient: 'from-blue-400 to-teal-600',
    isNew: true,
    popularity: 70,
  },
  {
    slug: 'ssl-checker',
    name: 'SSL Checker',
    description: 'Check SSL certificate details for any website.',
    category: 'Web Utilities',
    icon: Lock,
    gradient: 'from-emerald-400 to-cyan-600',
    isNew: true,
    popularity: 73,
  },
  {
    slug: 'website-screenshot',
    name: 'Website Screenshot',
    description: 'Capture screenshots of any website URL.',
    category: 'Web Utilities',
    icon: Camera,
    gradient: 'from-cyan-400 to-blue-600',
    isNew: true,
    popularity: 68,
  },
  {
    slug: 'open-graph-preview',
    name: 'Open Graph Preview',
    description: 'Preview how your site looks when shared on social media.',
    category: 'Web Utilities',
    icon: Share2,
    gradient: 'from-teal-400 to-blue-600',
    isNew: true,
    popularity: 71,
  },
  {
    slug: 'url-preview',
    name: 'URL Preview',
    description: 'Preview meta tags and content for any URL.',
    category: 'Web Utilities',
    icon: Link2,
    gradient: 'from-cyan-400 to-teal-600',
    isNew: true,
    popularity: 65,
  },
  {
    slug: 'qr-label-generator',
    name: 'QR Label Generator',
    description: 'Generate printable QR code labels for products.',
    category: 'Web Utilities',
    icon: Barcode,
    gradient: 'from-blue-400 to-cyan-600',
    isNew: true,
    popularity: 67,
  },
  {
    slug: 'website-manifest-generator',
    name: 'Website Manifest Generator',
    description: 'Generate PWA manifest files for your website.',
    category: 'Web Utilities',
    icon: FileJson,
    gradient: 'from-teal-400 to-cyan-600',
    isNew: true,
    popularity: 62,
  },
  {
    slug: 'notes',
    name: 'Notes',
    description: 'Take and save notes directly in your browser.',
    category: 'Productivity',
    icon: StickyNote,
    gradient: 'from-amber-400 to-yellow-600',
    isNew: true,
    popularity: 82,
  },
  {
    slug: 'to-do-list',
    name: 'To Do List',
    description: 'Create and manage tasks with a clean to-do list.',
    category: 'Productivity',
    icon: ListTodo,
    gradient: 'from-orange-400 to-amber-600',
    isNew: true,
    popularity: 85,
  },
  {
    slug: 'pomodoro-timer',
    name: 'Pomodoro Timer',
    description: 'Boost focus with a Pomodoro work-break timer.',
    category: 'Productivity',
    icon: Timer,
    gradient: 'from-red-400 to-orange-600',
    isNew: true,
    popularity: 80,
  },
  {
    slug: 'countdown-timer',
    name: 'Countdown Timer',
    description: 'Set a countdown to any date or event.',
    category: 'Productivity',
    icon: Clock,
    gradient: 'from-amber-400 to-red-600',
    isNew: true,
    popularity: 74,
  },
  {
    slug: 'stopwatch',
    name: 'Stopwatch',
    description: 'A precise stopwatch with lap timing support.',
    category: 'Productivity',
    icon: Timer,
    gradient: 'from-orange-400 to-amber-600',
    isNew: true,
    popularity: 76,
  },
  {
    slug: 'calendar',
    name: 'Calendar',
    description: 'View and navigate a monthly calendar.',
    category: 'Productivity',
    icon: Calendar,
    gradient: 'from-amber-400 to-orange-600',
    isNew: true,
    popularity: 72,
  },
  {
    slug: 'age-timeline',
    name: 'Age Timeline',
    description: 'Visualize your life timeline in weeks.',
    category: 'Productivity',
    icon: CalendarClock,
    gradient: 'from-orange-400 to-red-600',
    isNew: true,
    popularity: 68,
  },
  {
    slug: 'meeting-planner',
    name: 'Meeting Planner',
    description: 'Find the best meeting time across timezones.',
    category: 'Productivity',
    icon: MapPin,
    gradient: 'from-amber-400 to-orange-600',
    isNew: true,
    popularity: 70,
  },
  {
    slug: 'timezone-converter',
    name: 'Timezone Converter',
    description: 'Convert times between any world timezones.',
    category: 'Productivity',
    icon: Globe,
    gradient: 'from-orange-400 to-amber-600',
    isNew: true,
    popularity: 78,
  },
  {
    slug: 'business-day-calculator',
    name: 'Business Day Calculator',
    description: 'Calculate working days between two dates.',
    category: 'Productivity',
    icon: CalendarDays,
    gradient: 'from-amber-400 to-yellow-600',
    isNew: true,
    popularity: 66,
  },
];

categories.forEach((c) => {
  c.count = tools.filter((t) => t.category === c.name).length;
});

export const latestTools: Tool[] = [
  {
    slug: 'color-picker',
    name: 'Color Picker',
    description: 'Grab colors and copy HEX, RGB and HSL values.',
    category: 'Image Tools',
    icon: ImageLucide,
    gradient: 'from-fuchsia-400 to-pink-600',
    isNew: true,
    popularity: 64,
    addedDaysAgo: 1,
  },
  {
    slug: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Write Markdown and see live rendered output instantly.',
    category: 'Text Tools',
    icon: Type,
    gradient: 'from-cyan-400 to-blue-500',
    isNew: true,
    popularity: 58,
    addedDaysAgo: 3,
  },
];

export const mostPopularTools: Tool[] = [
  {
    slug: 'image-compressor',
    name: 'Image Compressor',
    description: 'Reduce image file size without losing visible quality.',
    category: 'Image Tools',
    icon: Gauge,
    gradient: 'from-fuchsia-400 to-purple-600',
    popularity: 95,
  },
  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Beautify, minify and validate JSON instantly.',
    category: 'Developer Tools',
    icon: Braces,
    gradient: 'from-violet-400 to-indigo-600',
    popularity: 93,
  },
  {
    slug: 'pdf-merge',
    name: 'PDF Merge',
    description: 'Combine multiple PDF files into one document.',
    category: 'PDF Tools',
    icon: FilePlus,
    gradient: 'from-rose-400 to-red-600',
    popularity: 92,
  },
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Create custom QR codes for links and text.',
    category: 'QR & Barcode Tools',
    icon: QrCode,
    gradient: 'from-emerald-400 to-teal-600',
    popularity: 98,
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    description: 'Create strong, secure passwords instantly.',
    category: 'Security Tools',
    icon: KeyRound,
    gradient: 'from-cyan-400 to-blue-500',
    popularity: 90,
  },
  {
    slug: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters and reading time.',
    category: 'Text Tools',
    icon: AlignLeft,
    gradient: 'from-sky-400 to-cyan-500',
    popularity: 88,
  },
];

export type Stat = {
  value: string;
  label: string;
  icon: LucideIcon;
};

export const stats: Stat[] = [
  { value: String(tools.length), label: 'Free Tools', icon: Zap },
  { value: String(categories.length), label: 'Categories', icon: Shield },
  { value: '100%', label: 'Free Forever', icon: Gauge },
  { value: '0', label: 'Sign-ups Needed', icon: ShieldCheck },
];

export function getToolsByCategory(categoryName: string): Tool[] {
  const cat = categories.find((c) => c.name === categoryName || c.slug === categoryName);
  if (!cat) return [];
  return tools.filter((t) => t.category === cat.name);
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getRelatedTools(slug: string, count = 3): Tool[] {
  const current = getToolBySlug(slug);
  if (!current) return tools.slice(0, count);
  const sameCategory = tools.filter(
    (t) => t.slug !== slug && t.category === current.category
  );
  const others = tools.filter(
    (t) => t.slug !== slug && t.category !== current.category
  );
  return [...sameCategory, ...others].slice(0, count);
}
