import type { DesignToolConfig } from '@/components/design/design-tool';

export const designToolConfigs: Record<string, DesignToolConfig> = {
  'color-palette-generator': { slug: 'color-palette-generator', label: 'Color Palette Generator', description: 'Generate palettes', showColorPicker: true, showGradientControls: false, showGlassControls: false, showNeumorphControls: false, showButtonControls: false, showShadowControls: false, showBorderRadiusControls: false, showSvgInput: false, showImageInput: false, showPlaceholderControls: false, showPaletteGenerator: true, actionLabel: 'Generate' },
  'gradient-generator': { slug: 'gradient-generator', label: 'Gradient Generator', description: 'Generate gradients', showColorPicker: true, showGradientControls: true, showGlassControls: false, showNeumorphControls: false, showButtonControls: false, showShadowControls: false, showBorderRadiusControls: false, showSvgInput: false, showImageInput: false, showPlaceholderControls: false, showPaletteGenerator: false, actionLabel: 'Generate' },
  'css-gradient-generator': { slug: 'css-gradient-generator', label: 'CSS Gradient Generator', description: 'Generate CSS gradients', showColorPicker: true, showGradientControls: true, showGlassControls: false, showNeumorphControls: false, showButtonControls: false, showShadowControls: false, showBorderRadiusControls: false, showSvgInput: false, showImageInput: false, showPlaceholderControls: false, showPaletteGenerator: false, actionLabel: 'Generate' },
  'glassmorphism-generator': { slug: 'glassmorphism-generator', label: 'Glassmorphism Generator', description: 'Generate glass CSS', showColorPicker: false, showGradientControls: false, showGlassControls: true, showNeumorphControls: false, showButtonControls: false, showShadowControls: false, showBorderRadiusControls: false, showSvgInput: false, showImageInput: false, showPlaceholderControls: false, showPaletteGenerator: false, actionLabel: 'Generate' },
  'neumorphism-generator': { slug: 'neumorphism-generator', label: 'Neumorphism Generator', description: 'Generate neumorphism CSS', showColorPicker: false, showGradientControls: false, showGlassControls: false, showNeumorphControls: true, showButtonControls: false, showShadowControls: false, showBorderRadiusControls: false, showSvgInput: false, showImageInput: false, showPlaceholderControls: false, showPaletteGenerator: false, actionLabel: 'Generate' },
  'css-button-generator': { slug: 'css-button-generator', label: 'CSS Button Generator', description: 'Generate CSS buttons', showColorPicker: true, showGradientControls: false, showGlassControls: false, showNeumorphControls: false, showButtonControls: true, showShadowControls: false, showBorderRadiusControls: false, showSvgInput: false, showImageInput: false, showPlaceholderControls: false, showPaletteGenerator: false, actionLabel: 'Generate' },
  'css-shadow-generator': { slug: 'css-shadow-generator', label: 'CSS Shadow Generator', description: 'Generate box shadows', showColorPicker: false, showGradientControls: false, showGlassControls: false, showNeumorphControls: false, showButtonControls: false, showShadowControls: true, showBorderRadiusControls: false, showSvgInput: false, showImageInput: false, showPlaceholderControls: false, showPaletteGenerator: false, actionLabel: 'Generate' },
  'border-radius-generator': { slug: 'border-radius-generator', label: 'Border Radius Generator', description: 'Generate border radius', showColorPicker: false, showGradientControls: false, showGlassControls: false, showNeumorphControls: false, showButtonControls: false, showShadowControls: false, showBorderRadiusControls: true, showSvgInput: false, showImageInput: false, showPlaceholderControls: false, showPaletteGenerator: false, actionLabel: 'Generate' },
  'svg-viewer': { slug: 'svg-viewer', label: 'SVG Viewer', description: 'View SVG', showColorPicker: false, showGradientControls: false, showGlassControls: false, showNeumorphControls: false, showButtonControls: false, showShadowControls: false, showBorderRadiusControls: false, showSvgInput: true, showImageInput: false, showPlaceholderControls: false, showPaletteGenerator: false, actionLabel: 'View' },
  'svg-optimizer': { slug: 'svg-optimizer', label: 'SVG Optimizer', description: 'Optimize SVG', showColorPicker: false, showGradientControls: false, showGlassControls: false, showNeumorphControls: false, showButtonControls: false, showShadowControls: false, showBorderRadiusControls: false, showSvgInput: true, showImageInput: false, showPlaceholderControls: false, showPaletteGenerator: false, actionLabel: 'Optimize' },
  'svg-to-png': { slug: 'svg-to-png', label: 'SVG to PNG', description: 'Convert SVG to PNG', showColorPicker: false, showGradientControls: false, showGlassControls: false, showNeumorphControls: false, showButtonControls: false, showShadowControls: false, showBorderRadiusControls: false, showSvgInput: true, showImageInput: false, showPlaceholderControls: false, showPaletteGenerator: false, actionLabel: 'Convert' },
  'png-to-svg': { slug: 'png-to-svg', label: 'PNG to SVG', description: 'Convert PNG to SVG', showColorPicker: false, showGradientControls: false, showGlassControls: false, showNeumorphControls: false, showButtonControls: false, showShadowControls: false, showBorderRadiusControls: false, showSvgInput: false, showImageInput: true, showPlaceholderControls: false, showPaletteGenerator: false, actionLabel: 'Convert' },
  'favicon-generator': { slug: 'favicon-generator', label: 'Favicon Generator', description: 'Generate favicon', showColorPicker: false, showGradientControls: false, showGlassControls: false, showNeumorphControls: false, showButtonControls: false, showShadowControls: false, showBorderRadiusControls: false, showSvgInput: false, showImageInput: true, showPlaceholderControls: false, showPaletteGenerator: false, actionLabel: 'Generate' },
  'image-placeholder-generator': { slug: 'image-placeholder-generator', label: 'Image Placeholder Generator', description: 'Generate placeholders', showColorPicker: false, showGradientControls: false, showGlassControls: false, showNeumorphControls: false, showButtonControls: false, showShadowControls: false, showBorderRadiusControls: false, showSvgInput: false, showImageInput: false, showPlaceholderControls: true, showPaletteGenerator: false, actionLabel: 'Generate' },
};
