import type { ProductivityToolConfig } from '@/components/productivity/productivity-tool';

export const productivityToolConfigs: Record<string, ProductivityToolConfig> = {
  'notes': { slug: 'notes', label: 'Notes', description: 'Take notes', isNotes: true, isTodoList: false, isPomodoro: false, isCountdown: false, isStopwatch: false, isCalendar: false, isAgeTimeline: false, isMeetingPlanner: false, isTimezoneConverter: false, isBusinessDayCalculator: false },
  'to-do-list': { slug: 'to-do-list', label: 'To Do List', description: 'Manage tasks', isNotes: false, isTodoList: true, isPomodoro: false, isCountdown: false, isStopwatch: false, isCalendar: false, isAgeTimeline: false, isMeetingPlanner: false, isTimezoneConverter: false, isBusinessDayCalculator: false },
  'pomodoro-timer': { slug: 'pomodoro-timer', label: 'Pomodoro Timer', description: 'Pomodoro timer', isNotes: false, isTodoList: false, isPomodoro: true, isCountdown: false, isStopwatch: false, isCalendar: false, isAgeTimeline: false, isMeetingPlanner: false, isTimezoneConverter: false, isBusinessDayCalculator: false },
  'countdown-timer': { slug: 'countdown-timer', label: 'Countdown Timer', description: 'Countdown', isNotes: false, isTodoList: false, isPomodoro: false, isCountdown: true, isStopwatch: false, isCalendar: false, isAgeTimeline: false, isMeetingPlanner: false, isTimezoneConverter: false, isBusinessDayCalculator: false },
  'stopwatch': { slug: 'stopwatch', label: 'Stopwatch', description: 'Stopwatch', isNotes: false, isTodoList: false, isPomodoro: false, isCountdown: false, isStopwatch: true, isCalendar: false, isAgeTimeline: false, isMeetingPlanner: false, isTimezoneConverter: false, isBusinessDayCalculator: false },
  'calendar': { slug: 'calendar', label: 'Calendar', description: 'Calendar', isNotes: false, isTodoList: false, isPomodoro: false, isCountdown: false, isStopwatch: false, isCalendar: true, isAgeTimeline: false, isMeetingPlanner: false, isTimezoneConverter: false, isBusinessDayCalculator: false },
  'age-timeline': { slug: 'age-timeline', label: 'Age Timeline', description: 'Life timeline', isNotes: false, isTodoList: false, isPomodoro: false, isCountdown: false, isStopwatch: false, isCalendar: false, isAgeTimeline: true, isMeetingPlanner: false, isTimezoneConverter: false, isBusinessDayCalculator: false },
  'meeting-planner': { slug: 'meeting-planner', label: 'Meeting Planner', description: 'Plan meetings', isNotes: false, isTodoList: false, isPomodoro: false, isCountdown: false, isStopwatch: false, isCalendar: false, isAgeTimeline: false, isMeetingPlanner: true, isTimezoneConverter: false, isBusinessDayCalculator: false },
  'timezone-converter': { slug: 'timezone-converter', label: 'Timezone Converter', description: 'Convert timezones', isNotes: false, isTodoList: false, isPomodoro: false, isCountdown: false, isStopwatch: false, isCalendar: false, isAgeTimeline: false, isMeetingPlanner: false, isTimezoneConverter: true, isBusinessDayCalculator: false },
  'business-day-calculator': { slug: 'business-day-calculator', label: 'Business Day Calculator', description: 'Calculate business days', isNotes: false, isTodoList: false, isPomodoro: false, isCountdown: false, isStopwatch: false, isCalendar: false, isAgeTimeline: false, isMeetingPlanner: false, isTimezoneConverter: false, isBusinessDayCalculator: true },
};
