import type { Tool } from '@/lib/data';

type Enhancement = {
  titleSuffix: string;
  description: string;
};

const enhancements: Record<string, Enhancement> = {
  'qr-code-generator': { titleSuffix: 'Create QR Codes Online Free', description: 'Create custom QR codes for URLs, text, WiFi, and more. Customize colors, add logos, and download as SVG or PNG — free, no sign-up.' },
  'background-remover': { titleSuffix: 'Remove Image Backgrounds Online Free', description: 'Remove image backgrounds automatically in your browser. No upload to a server — your photos stay private. Download as PNG with transparency.' },
  'image-watermark': { titleSuffix: 'Add Watermarks to Images Online Free', description: 'Add text or logo watermarks to protect your images. Adjust opacity, position, and size — all in your browser, no upload required.' },
  'image-rotator': { titleSuffix: 'Rotate Images Online Free', description: 'Rotate images by 90, 180, 270 or any custom angle with live preview. Supports JPG, PNG, and WebP — free, in your browser.' },
  'image-flipper': { titleSuffix: 'Flip Images Online Free', description: 'Flip images horizontally or vertically instantly. Works with JPG, PNG, and WebP formats — free, no upload, no sign-up.' },
  'image-color-picker': { titleSuffix: 'Pick Colors from Images Online Free', description: 'Pick exact hex and RGB colors from any point in an image. Zoom in for pixel-precise selection — free, in your browser.' },
  'image-blur': { titleSuffix: 'Blur Images Online Free', description: 'Apply adjustable blur effects to your images with a slider. Great for backgrounds, privacy, and focus effects — free, no upload.' },
  'image-sharpen': { titleSuffix: 'Sharpen Images Online Free', description: 'Sharpen blurry images with adjustable intensity. Improve detail and clarity in photos — free, all processing in your browser.' },
  'image-brightness-adjuster': { titleSuffix: 'Adjust Image Brightness', description: 'Adjust the brightness of any image with a slider. Brighten dark photos or dim overexposed ones — free, no upload required.' },
  'image-contrast-adjuster': { titleSuffix: 'Adjust Image Contrast Online Free', description: 'Fine-tune image contrast with live preview. Enhance dull photos or soften harsh ones — free, all in your browser.' },
  'image-grayscale': { titleSuffix: 'Convert Images to Grayscale Online Free', description: 'Convert images to grayscale instantly. Turn color photos to black and white for artistic effect — free, no upload, no sign-up.' },
  'image-sepia-filter': { titleSuffix: 'Apply Sepia Filter Online Free', description: 'Apply a vintage sepia tone to your images. Create classic film-style effects with one click — free, all processing in your browser.' },
  'image-border-creator': { titleSuffix: 'Add Borders to Images Online Free', description: 'Add custom borders with adjustable width and color to any image. Choose from multiple border styles — free, no upload required.' },
  'image-rounded-corners': { titleSuffix: 'Round Image Corners Online Free', description: 'Round the corners of any image with adjustable radius control. Great for avatars and thumbnails — free, in your browser.' },
  'image-metadata-viewer': { titleSuffix: 'View Image EXIF Metadata', description: 'View EXIF, IPTC and XMP metadata embedded in your images. See camera model, GPS, timestamp and more — free, no upload.' },
  'image-metadata-remover': { titleSuffix: 'Remove Image EXIF Metadata', description: 'Strip EXIF, IPTC and XMP metadata from images for privacy. Remove GPS, camera data and timestamps — free, all in your browser.' },
  'pdf-rotate': { titleSuffix: 'Rotate PDF Pages Online Free', description: 'Rotate PDF pages 90, 180 or 270 degrees. Fix sideways or upside-down pages — free, no upload, no sign-up.' },
  'pdf-unlock': { titleSuffix: 'Remove PDF Password Online Free', description: 'Remove password protection from PDF files. Unlock PDFs you own so you can edit and share them — free, in your browser.' },
  'pdf-protect': { titleSuffix: 'Password Protect PDF Online Free', description: 'Add password protection to your PDF documents. Secure sensitive files before sharing — free, no upload, no sign-up.' },
  'pdf-page-number': { titleSuffix: 'Add Page Numbers to PDF Online Free', description: 'Add page numbers to PDF documents automatically. Choose position, format and starting number — free, all in your browser.' },
  'pdf-delete-pages': { titleSuffix: 'Delete PDF Pages Online Free', description: 'Remove unwanted pages from PDF files. Delete blank, duplicate or incorrect pages and download the result — free, no upload.' },
  'pdf-extract-pages': { titleSuffix: 'Extract PDF Pages Online Free', description: 'Extract specific pages from a PDF into a new file. Keep only the pages you need — free, all processing in your browser.' },
  'pdf-reorder-pages': { titleSuffix: 'Reorder PDF Pages Online Free', description: 'Rearrange PDF pages in any order with drag and drop. Move pages around visually and download the result — free, no upload.' },
  'pdf-watermark': { titleSuffix: 'Add Watermark to PDF Online Free', description: 'Add text watermarks to PDF documents. Protect your PDFs with custom watermark text, opacity and position — free, in your browser.' },
  'pdf-metadata-editor': { titleSuffix: 'Edit PDF Metadata Online Free', description: 'Edit title, author, subject and keywords in PDF files. Update document properties without any software — free, no upload.' },
  'pdf-viewer': { titleSuffix: 'View PDF Files Online Free', description: 'View and read PDF files directly in your browser. No download or plugin required — open any PDF instantly, free.' },
  'text-repeater': { titleSuffix: 'Repeat Text Online Free', description: 'Repeat any text multiple times with custom separators. Generate repeated strings for testing or formatting — free, no sign-up.' },
  'text-reverser': { titleSuffix: 'Reverse Text Online Free', description: 'Reverse text character by character or line by line. Flip words, sentences or entire paragraphs instantly — free, no sign-up.' },
  'random-text-generator': { titleSuffix: 'Generate Random Text Online Free', description: 'Generate random words, sentences and paragraphs. Useful for testing, placeholder content and data generation — free, no sign-up.' },
  'line-counter': { titleSuffix: 'Count Lines in Text Online Free', description: 'Count lines, words and characters in your text. Get instant statistics for any text input — free, no sign-up required.' },
  'remove-extra-spaces': { titleSuffix: 'Remove Extra Spaces Online Free', description: 'Clean up multiple spaces, tabs and blank lines from text. Normalize whitespace for clean, consistent formatting — free, no sign-up.' },
  'text-compare': { titleSuffix: 'Compare Text Online Free', description: 'Compare two text blocks and highlight differences. Spot additions, deletions and changes between versions — free, no sign-up.' },
  'find-and-replace': { titleSuffix: 'Find & Replace Text Online Free', description: 'Find and replace text with regex support. Batch replace words, patterns or special characters across any text — free, no sign-up.' },
  'text-cleaner': { titleSuffix: 'Clean Text Online Free', description: 'Remove formatting, special characters and clean up text. Strip HTML tags, non-printable chars and extra whitespace — free, no sign-up.' },
  'markdown-preview': { titleSuffix: 'Preview Markdown Online Free', description: 'Write Markdown and see live rendered output instantly. Preview headings, lists, code blocks and links — free, no sign-up required.' },
  'html-to-text': { titleSuffix: 'Convert HTML to Text Online Free', description: 'Convert HTML markup to clean plain text. Strip all tags and extract readable content from any HTML — free, no sign-up.' },
  'password-encryptor': { titleSuffix: 'Encrypt Text Online Free', description: 'Encrypt text with AES-GCM 256-bit encryption and a password. Secure sensitive messages before sharing — free, all in your browser.' },
  'password-decryptor': { titleSuffix: 'Decrypt Text Online Free', description: 'Decrypt AES-GCM encrypted text with a password. Recover encrypted messages in your browser — free, no upload required.' },
  'random-pin-generator': { titleSuffix: 'Generate Random PINs Online Free', description: 'Generate secure random PINs of any length from 4 to 12 digits. Uses Web Crypto API for true randomness — free, no sign-up.' },
  'random-number-generator': { titleSuffix: 'Generate Random Numbers', description: 'Generate random numbers within a custom range. Set min, max and count for bulk generation — free, no sign-up required.' },
  'otp-generator': { titleSuffix: 'Generate OTP Codes Online Free', description: 'Generate one-time passwords using TOTP and HOTP algorithms. Create 2FA codes for testing — free, all in your browser.' },
  'hash-compare': { titleSuffix: 'Compare Hashes Online Free', description: 'Compare two hashes to check if they match. Verify file integrity and detect changes — free, no sign-up required.' },
  'bcrypt-generator': { titleSuffix: 'Generate bcrypt Hashes Online Free', description: 'Generate bcrypt password hashes with adjustable rounds from 4 to 12. Secure password hashing for developers — free, in your browser.' },
  'sha1-hash-generator': { titleSuffix: 'Generate SHA1 Hashes Online Free', description: 'Generate SHA1 hashes from any text input. Compute SHA-1 checksums for data verification — free, no sign-up required.' },
  'base32-encoder': { titleSuffix: 'Encode Base32 Online Free', description: 'Encode text to Base32 format instantly. Convert strings to Base32 for encoding and transport — free, no sign-up required.' },
  'base32-decoder': { titleSuffix: 'Decode Base32 Online Free', description: 'Decode Base32 encoded text back to plain text. Convert Base32 strings to readable content — free, no sign-up required.' },
  'uuid-bulk-generator': { titleSuffix: 'Generate UUIDs in Bulk Online Free', description: 'Generate multiple UUIDs at once with custom count up to 1000. Create unique identifiers for databases and apps — free, no sign-up.' },
  'jwt-decoder': { titleSuffix: 'Decode JWT Tokens Online Free', description: 'Decode JWT tokens and inspect header and payload. View claims, expiration and issuer data — free, all in your browser.' },
  'jwt-encoder': { titleSuffix: 'Create JWT Tokens Online Free', description: 'Create JWT tokens from header and payload JSON. Generate signed JSON Web Tokens for testing — free, no sign-up required.' },
  'sql-formatter': { titleSuffix: 'Format SQL Online Free', description: 'Format and beautify SQL queries instantly. Support for MySQL, PostgreSQL, SQL Server syntax — free, no sign-up required.' },
  'xml-formatter': { titleSuffix: 'Format XML Online Free', description: 'Beautify and format XML documents with proper indentation. Pretty-print messy XML for readability — free, no sign-up required.' },
  'xml-validator': { titleSuffix: 'Validate XML Online Free', description: 'Validate XML syntax and find errors instantly. Check well-formedness and get error locations — free, no sign-up required.' },
  'csv-to-json': { titleSuffix: 'Convert CSV to JSON Online Free', description: 'Convert CSV data to structured JSON format. Handles quoted fields, commas and various delimiters — free, all in your browser.' },
  'json-to-csv': { titleSuffix: 'Convert JSON to CSV Online Free', description: 'Convert JSON data to CSV format instantly. Flatten JSON arrays into spreadsheet-ready CSV — free, no sign-up required.' },
  'yaml-formatter': { titleSuffix: 'Format YAML Online Free', description: 'Format and beautify YAML documents with proper indentation. Clean up messy YAML for readability — free, no sign-up required.' },
  'yaml-validator': { titleSuffix: 'Validate YAML Online Free', description: 'Validate YAML syntax and find errors quickly. Check indentation and structure issues — free, no sign-up required.' },
  'color-converter': { titleSuffix: 'Convert Colors Online Free', description: 'Convert colors between HEX, RGB, HSL and CMYK formats. Get instant color conversions for design and CSS — free, no sign-up.' },
  'hex-to-rgb': { titleSuffix: 'Convert HEX to RGB Online Free', description: 'Convert HEX color codes to RGB values instantly. Get red, green and blue components from any hex color — free, no sign-up.' },
  'rgb-to-hex': { titleSuffix: 'Convert RGB to HEX Online Free', description: 'Convert RGB color values to HEX codes instantly. Get hex color strings from red, green and blue values — free, no sign-up.' },
  'timestamp-converter': { titleSuffix: 'Convert Unix Timestamps Online Free', description: 'Convert Unix timestamps to human-readable dates and times. Supports seconds and milliseconds — free, no sign-up required.' },
  'unix-time-converter': { titleSuffix: 'Convert Unix Time Online Free', description: 'Convert dates to Unix timestamps and back. Get epoch time for any date or convert epoch to readable format — free, no sign-up.' },
  'hreflang-generator': { titleSuffix: 'Generate hreflang Tags Online Free', description: 'Generate hreflang tags for international SEO. Create correct language and region annotations for multi-language sites — free, no sign-up.' },
  'schema-markup-generator': { titleSuffix: 'Generate Schema.org JSON-LD', description: 'Generate schema.org JSON-LD structured data for rich search results. Support for articles, products, events and more — free, no sign-up.' },
  'faq-schema-generator': { titleSuffix: 'Generate FAQ Schema Online Free', description: 'Generate FAQ schema markup for rich results in Google search. Create valid JSON-LD FAQPage structured data — free, no sign-up.' },
  'breadcrumb-schema-generator': { titleSuffix: 'Generate Breadcrumb Schema', description: 'Generate breadcrumb schema markup for SEO. Create valid JSON-LD BreadcrumbList structured data — free, no sign-up required.' },
  'article-schema-generator': { titleSuffix: 'Generate Article Schema', description: 'Generate article schema markup for blog posts. Create valid JSON-LD Article structured data for rich results — free, no sign-up.' },
  'product-schema-generator': { titleSuffix: 'Generate Product Schema', description: 'Generate product schema markup for e-commerce SEO. Create valid JSON-LD Product structured data with offers — free, no sign-up.' },
  'website-schema-generator': { titleSuffix: 'Generate Website Schema', description: 'Generate website schema markup for your site. Create valid JSON-LD WebSite structured data with search action — free, no sign-up.' },
  'meta-robots-generator': { titleSuffix: 'Generate Meta Robots Tags', description: 'Generate meta robots tags for crawl control. Set index, follow, noarchive and more directives — free, no sign-up required.' },
  'keyword-extractor': { titleSuffix: 'Extract Keywords Online Free', description: 'Extract keywords and key phrases from any text. Identify important terms for SEO and content analysis — free, no sign-up required.' },
  'serp-pixel-checker': { titleSuffix: 'Check SERP Pixel Width Online Free', description: 'Check pixel width of titles and meta descriptions for Google SERP. Ensure your snippets display correctly — free, no sign-up.' },
  'speed-converter': { titleSuffix: 'Convert Speed Units Online Free', description: 'Convert between m/s, km/h, mph, knots and more speed units. Fast, accurate speed conversions — free, no sign-up required.' },
  'area-converter': { titleSuffix: 'Convert Area Units Online Free', description: 'Convert between square metres, acres, hectares, square feet and more area units — free, no sign-up required.' },
  'volume-converter': { titleSuffix: 'Convert Volume Units Online Free', description: 'Convert between litres, gallons, cups, millilitres and more volume units — free, no sign-up required.' },
  'pressure-converter': { titleSuffix: 'Convert Pressure Units Online Free', description: 'Convert between pascals, bar, psi, atmospheres and more pressure units — free, no sign-up required.' },
  'energy-converter': { titleSuffix: 'Convert Energy Units Online Free', description: 'Convert between joules, calories, kWh, BTUs and more energy units — free, no sign-up required.' },
  'power-converter': { titleSuffix: 'Convert Power Units Online Free', description: 'Convert between watts, horsepower, kilowatts and more power units — free, no sign-up required.' },
  'fuel-converter': { titleSuffix: 'Convert Fuel Economy Online Free', description: 'Convert between MPG, L/100km and km/L fuel economy units. Compare fuel efficiency across regions — free, no sign-up.' },
  'currency-converter': { titleSuffix: 'Convert Currencies Online Free', description: 'Convert currencies using your own exchange rates. Supports all major world currencies with custom rate input — free, no sign-up.' },
  'ai-blog-title-generator': { titleSuffix: 'Generate Blog Titles Online Free', description: 'Generate catchy blog titles from your topic. Create multiple headline variations to choose from — free AI-powered tool, no sign-up.' },
  'ai-blog-outline-generator': { titleSuffix: 'Create Blog Outlines', description: 'Create structured blog post outlines instantly. Generate heading hierarchies and section ideas from your topic — free, no sign-up.' },
  'ai-article-idea-generator': { titleSuffix: 'Generate Article Ideas', description: 'Brainstorm fresh article ideas from any keyword. Get multiple creative angles and topics for your content — free, no sign-up required.' },
  'ai-paragraph-generator': { titleSuffix: 'Generate Paragraphs Online Free', description: 'Generate well-structured paragraphs on any topic. Create draft content for blogs, essays and reports — free AI tool, no sign-up.' },
  'ai-sentence-rewriter': { titleSuffix: 'Rewrite Sentences Online Free', description: 'Rewrite sentences to improve flow and clarity. Get alternative phrasings while keeping your original meaning — free, no sign-up.' },
  'ai-grammar-improver': { titleSuffix: 'Fix Grammar Online Free', description: 'Fix grammar and spelling errors automatically. Improve your writing with AI-powered corrections — free, no sign-up required.' },
  'ai-summarizer': { titleSuffix: 'Summarize Text Online Free', description: 'Summarize long text into key points instantly. Get concise summaries of articles, documents and essays — free, no sign-up required.' },
  'ai-expand-text': { titleSuffix: 'Expand Text Online Free', description: 'Expand short text into detailed paragraphs. Add depth and detail to brief notes or outlines — free AI-powered tool, no sign-up.' },
  'ai-simplify-text': { titleSuffix: 'Simplify Text Online Free', description: 'Simplify complex text into easy-to-read language. Make technical or academic content more accessible — free, no sign-up required.' },
  'ai-humanize-text': { titleSuffix: 'Humanize AI Text Online Free', description: 'Make AI-generated text sound natural and human. Improve tone and readability of machine-written content — free, no sign-up.' },
  'ai-meta-title-generator': { titleSuffix: 'Generate Meta Titles Online Free', description: 'Generate SEO-optimized meta titles for pages. Create compelling, keyword-rich titles under 60 characters — free, no sign-up.' },
  'ai-meta-description-generator': { titleSuffix: 'Generate Meta Descriptions', description: 'Create compelling meta descriptions for SEO. Generate 150-160 character descriptions that improve click-through rates — free, no sign-up.' },
  'ai-keyword-generator': { titleSuffix: 'Generate Keywords Online Free', description: 'Generate targeted keywords for your content. Discover relevant terms for SEO and PPC campaigns — free, no sign-up required.' },
  'ai-faq-generator': { titleSuffix: 'Generate FAQs Online Free', description: 'Generate FAQs with answers from your topic. Create question-and-answer pairs for pages and articles — free, no sign-up required.' },
  'ai-seo-outline-generator': { titleSuffix: 'Create SEO Outlines Online Free', description: 'Create SEO-optimized content outlines instantly. Generate heading structures with keyword suggestions — free, no sign-up.' },
  'ai-slug-generator-pro': { titleSuffix: 'Generate URL Slugs Online Free', description: 'Generate clean, SEO-friendly URL slugs. Convert titles to URL-safe strings with proper hyphenation — free, no sign-up required.' },
  'ai-product-schema-writer': { titleSuffix: 'Generate Product Schema', description: 'Generate product schema markup automatically. Create JSON-LD structured data for e-commerce product pages — free, no sign-up.' },
  'ai-alt-text-generator': { titleSuffix: 'Generate Alt Text Online Free', description: 'Generate descriptive alt text for images. Improve accessibility and SEO with AI-powered image descriptions — free, no sign-up.' },
  'ai-instagram-caption-generator': { titleSuffix: 'Create IG Captions', description: 'Generate engaging Instagram captions instantly. Create captions with hashtags and emojis from your topic — free, no sign-up.' },
  'ai-facebook-caption-generator': { titleSuffix: 'Generate Facebook Captions', description: 'Create engaging Facebook post captions. Generate compelling text with hooks and call-to-actions — free, no sign-up required.' },
  'ai-linkedin-post-generator': { titleSuffix: 'Generate LinkedIn Posts', description: 'Generate professional LinkedIn posts in seconds. Create networking content with the right tone for your audience — free, no sign-up.' },
  'ai-tweet-generator': { titleSuffix: 'Generate Tweets Online Free', description: 'Generate catchy tweets that drive engagement. Create Twitter posts within character limits from your topic — free, no sign-up.' },
  'ai-pinterest-pin-title-generator': { titleSuffix: 'Create Pin Titles', description: 'Generate click-worthy Pinterest pin titles. Create SEO-optimized titles that attract saves and clicks — free, no sign-up.' },
  'ai-pinterest-description-generator': { titleSuffix: 'Create Pin Descs', description: 'Create SEO-optimized Pinterest descriptions. Generate keyword-rich pin descriptions that improve discovery — free, no sign-up.' },
  'ai-hashtag-generator': { titleSuffix: 'Generate Hashtags Online Free', description: 'Generate trending hashtags for any topic. Discover relevant hashtags for Instagram, Twitter and TikTok — free, no sign-up required.' },
  'ai-social-bio-generator': { titleSuffix: 'Generate Social Bios Online Free', description: 'Generate catchy bios for social media profiles. Create professional or creative bios for Instagram, Twitter and LinkedIn — free, no sign-up.' },
  'ai-youtube-title-generator': { titleSuffix: 'Generate YouTube Titles', description: 'Generate clickable YouTube video titles. Create compelling titles that improve click-through rates — free, no sign-up required.' },
  'ai-youtube-description-generator': { titleSuffix: 'Create YT Descriptions', description: 'Create SEO-optimized YouTube descriptions. Generate detailed descriptions with timestamps and keywords — free, no sign-up.' },
  'ai-video-hook-generator': { titleSuffix: 'Generate Video Hooks Online Free', description: 'Generate attention-grabbing video hooks. Create opening lines that keep viewers watching past the first 3 seconds — free, no sign-up.' },
  'ai-video-script-generator': { titleSuffix: 'Generate Video Scripts', description: 'Generate complete video scripts from your topic. Create structured scripts with scenes, voiceover and visual cues — free, no sign-up.' },
  'ai-shorts-caption-generator': { titleSuffix: 'Generate Shorts Captions', description: 'Generate captions for YouTube Shorts and Reels. Create short-form video captions with hooks and hashtags — free, no sign-up.' },
  'ai-thumbnail-text-generator': { titleSuffix: 'Generate Thumbnail Text', description: 'Generate punchy text overlays for thumbnails. Create eye-catching short text for video thumbnails — free, no sign-up required.' },
  'ai-business-name-generator': { titleSuffix: 'Generate Business Names', description: 'Generate creative business name ideas. Get multiple name suggestions for your startup or company — free, no sign-up required.' },
  'ai-startup-name-generator': { titleSuffix: 'Generate Startup Names', description: 'Generate catchy startup name ideas. Get unique, memorable names for your new venture — free, no sign-up required.' },
  'ai-brand-name-generator': { titleSuffix: 'Generate Brand Names Online Free', description: 'Generate memorable brand name ideas. Create distinctive names for your brand or product line — free, no sign-up required.' },
  'ai-slogan-generator': { titleSuffix: 'Generate Slogans Online Free', description: 'Generate catchy slogans for your brand. Create memorable tagline phrases that capture your brand identity — free, no sign-up.' },
  'ai-tagline-generator': { titleSuffix: 'Generate Taglines Online Free', description: 'Generate memorable taglines for your business. Create short, impactful phrases for marketing — free, no sign-up required.' },
  'ai-product-description-generator': { titleSuffix: 'Create Product Copy', description: 'Generate compelling product descriptions for e-commerce. Create persuasive copy that highlights features and benefits — free, no sign-up.' },
  'ai-marketing-copy-generator': { titleSuffix: 'Generate Marketing Copy', description: 'Generate persuasive marketing copy instantly. Create ad copy, landing page text and email content — free, no sign-up required.' },
  'ai-email-writer': { titleSuffix: 'Write Emails Online Free', description: 'Generate professional emails from your prompt. Create business emails, newsletters and outreach messages — free, no sign-up required.' },
  'ai-cold-email-generator': { titleSuffix: 'Generate Cold Emails Online Free', description: 'Generate cold outreach emails that get replies. Create personalized cold emails with compelling subject lines — free, no sign-up.' },
  'ai-follow-up-email-generator': { titleSuffix: 'Generate Follow-up Emails', description: 'Generate follow-up emails that drive responses. Create polite, effective follow-up messages for any context — free, no sign-up.' },
  'ai-professional-reply-generator': { titleSuffix: 'Generate Email Replies', description: 'Generate professional email replies instantly. Create well-toned responses for business correspondence — free, no sign-up.' },
  'ai-resume-summary-generator': { titleSuffix: 'Generate Resume Summaries', description: 'Generate compelling resume summaries. Create professional summary statements that highlight your experience — free, no sign-up.' },
  'ai-cover-letter-generator': { titleSuffix: 'Generate Cover Letters', description: 'Generate professional cover letters instantly. Create tailored cover letters from your job details — free, no sign-up required.' },
  'ai-job-description-generator': { titleSuffix: 'Generate Job Descriptions', description: 'Generate detailed job descriptions for any role. Create postings with responsibilities, requirements and qualifications — free, no sign-up.' },
  'ai-interview-questions-generator': { titleSuffix: 'Create Interview Qs', description: 'Generate interview questions for any role. Create behavioral and technical questions for hiring — free, no sign-up required.' },
  'ai-amazon-listing-generator': { titleSuffix: 'Generate Amazon Listings', description: 'Generate optimized Amazon product listings. Create titles, bullet points and descriptions with keywords — free, no sign-up.' },
  'ai-shopify-product-description-generator': { titleSuffix: 'Shopify Copy', description: 'Generate product descriptions for Shopify stores. Create SEO-friendly copy that converts visitors to buyers — free, no sign-up.' },
  'ai-etsy-product-description-generator': { titleSuffix: 'Write Etsy Copy', description: 'Generate product descriptions for Etsy shops. Create compelling copy that highlights handmade and unique items — free, no sign-up.' },
  'ai-ebay-listing-generator': { titleSuffix: 'Generate eBay Listings', description: 'Generate optimized eBay product listings. Create titles and descriptions that improve search visibility — free, no sign-up.' },
  'video-compressor': { titleSuffix: 'Compress Video Online Free', description: 'Reduce video file size without losing visible quality. Adjust bitrate and resolution — free, all processing in your browser, no upload.' },
  'video-converter': { titleSuffix: 'Convert Video Formats Online Free', description: 'Convert videos between MP4, WebM, AVI and more formats. Change codec and container without uploading — free, in your browser.' },
  'video-trimmer': { titleSuffix: 'Trim Video Online Free', description: 'Trim and cut video to keep only the parts you need. Set start and end points with live preview — free, no upload required.' },
  'video-cutter': { titleSuffix: 'Cut Video Online Free', description: 'Cut out unwanted sections from any video file. Remove parts with precise frame control — free, all processing in your browser.' },
  'video-merger': { titleSuffix: 'Merge Videos Online Free', description: 'Combine multiple video clips into one file. Join videos in any order and download the result — free, no upload to a server.' },
  'video-splitter': { titleSuffix: 'Split Video Online Free', description: 'Split a video into multiple equal or custom segments. Break long videos into shorter clips — free, all in your browser.' },
  'video-rotator': { titleSuffix: 'Rotate Video Online Free', description: 'Rotate videos 90, 180 or 270 degrees instantly. Fix orientation issues from phone recordings — free, no upload required.' },
  'video-cropper': { titleSuffix: 'Crop Video Online Free', description: 'Crop video frames to any aspect ratio or dimension. Remove unwanted edges or fit specific dimensions — free, in your browser.' },
  'video-speed-controller': { titleSuffix: 'Change Video Speed Online Free', description: 'Speed up or slow down video playback speed. Create time-lapse or slow-motion effects — free, no upload required.' },
  'reverse-video': { titleSuffix: 'Reverse Video Online Free', description: 'Play any video in reverse for creative effects. Create backwards video clips with one click — free, all processing in your browser.' },
  'mute-video': { titleSuffix: 'Mute Video Online Free', description: 'Remove audio from any video file instantly. Create silent video clips for GIFs or background use — free, no upload required.' },
  'extract-audio': { titleSuffix: 'Extract Audio from Video Online Free', description: 'Pull the audio track out of any video file. Save audio as MP3 or WAV from video — free, all processing in your browser.' },
  'video-to-gif': { titleSuffix: 'Convert Video to GIF Online Free', description: 'Convert any video clip into an animated GIF. Set start time, duration and frame rate — free, no upload to a server.' },
  'gif-to-video': { titleSuffix: 'Convert GIF to Video Online Free', description: 'Convert animated GIFs to MP4 or WebM video. Reduce file size and improve compatibility — free, all in your browser.' },
  'video-watermark': { titleSuffix: 'Add Watermark to Video Online Free', description: 'Add text or image watermarks to your videos. Protect content with custom overlay positioning — free, no upload required.' },
  'video-thumbnail-generator': { titleSuffix: 'Extract Video Thumbnails', description: 'Extract frames from videos as thumbnail images. Capture specific moments as PNG or JPG — free, all in your browser.' },
  'video-metadata-viewer': { titleSuffix: 'View Video Metadata Online Free', description: 'Inspect codec, resolution, duration, bitrate and more video metadata. View detailed file information — free, no upload.' },
  'video-metadata-remover': { titleSuffix: 'Remove Video Metadata Online Free', description: 'Strip metadata from video files for privacy. Remove location, device and timestamp data — free, all in your browser.' },
  'audio-converter': { titleSuffix: 'Convert Audio Formats Online Free', description: 'Convert audio between MP3, WAV, OGG, AAC and more formats. Change sample rate and bitrate — free, all in your browser.' },
  'mp3-cutter': { titleSuffix: 'Cut MP3 Online Free', description: 'Cut MP3 files to keep only the parts you need. Trim audio with precise start and end points — free, no upload required.' },
  'audio-trimmer': { titleSuffix: 'Trim Audio Online Free', description: 'Trim silence and unwanted parts from audio files. Remove dead air and clean up recordings — free, all in your browser.' },
  'audio-compressor': { titleSuffix: 'Compress Audio Online Free', description: 'Reduce audio file size without losing quality. Adjust bitrate to find the right size-to-quality balance — free, no upload.' },
  'merge-audio': { titleSuffix: 'Merge Audio Files Online Free', description: 'Combine multiple audio files into one track. Join MP3, WAV or OGG files in any order — free, all processing in your browser.' },
  'reverse-audio': { titleSuffix: 'Reverse Audio Online Free', description: 'Play any audio file in reverse instantly. Create backwards audio effects for music or sound design — free, no upload.' },
  'volume-booster': { titleSuffix: 'Boost Audio Volume Online Free', description: 'Increase audio volume up to 3x without distortion. Make quiet recordings louder — free, all processing in your browser.' },
  'audio-speed-changer': { titleSuffix: 'Change Audio Speed Online Free', description: 'Change audio playback speed without changing pitch. Speed up or slow down recordings — free, no upload required.' },
  'pitch-changer': { titleSuffix: 'Change Audio Pitch Online Free', description: 'Shift the pitch of any audio file up or down. Change key without affecting tempo — free, all in your browser.' },
  'voice-recorder': { titleSuffix: 'Record Audio Online Free', description: 'Record audio from your microphone directly in the browser. No software install needed — free, saves as WAV or WebM.' },
  'text-to-speech': { titleSuffix: 'Convert Text to Speech Online Free', description: 'Convert written text into natural-sounding speech. Choose voices and adjust speed — free, no sign-up, in your browser.' },
  'speech-to-text': { titleSuffix: 'Transcribe Speech to Text Online Free', description: 'Transcribe spoken audio into text using your browser speech recognition. Convert voice to written words — free, no sign-up.' },
  'audio-metadata-viewer': { titleSuffix: 'View Audio Metadata Online Free', description: 'View ID3 tags, bitrate, codec and duration info for audio files. Inspect MP3, WAV and OGG metadata — free, no upload.' },
  'audio-metadata-remover': { titleSuffix: 'Remove Audio Metadata Online Free', description: 'Remove ID3 tags and metadata from audio files for privacy. Strip artist, album and track info — free, all in your browser.' },
  'word-to-pdf': { titleSuffix: 'Convert Word to PDF Online Free', description: 'Convert DOCX documents to PDF in your browser. No upload to a server — your Word files stay private. Free, no sign-up.' },
  'excel-to-pdf': { titleSuffix: 'Convert Excel to PDF Online Free', description: 'Convert XLSX spreadsheets to PDF format. Preserve layout and formatting — free, all processing in your browser, no upload.' },
  'powerpoint-to-pdf': { titleSuffix: 'Convert PowerPoint to PDF Online Free', description: 'Convert PPTX presentations to PDF. Keep slides and formatting intact — free, no upload to a server, no sign-up required.' },
  'pdf-to-word': { titleSuffix: 'Convert PDF to Word Online Free', description: 'Convert PDF documents to editable DOCX files. Extract text and layout for editing — free, all in your browser, no upload.' },
  'pdf-to-excel': { titleSuffix: 'Convert PDF to Excel Online Free', description: 'Extract tables from PDF into XLSX format. Convert PDF data to editable spreadsheets — free, all processing in your browser.' },
  'pdf-to-powerpoint': { titleSuffix: 'Convert PDF to PowerPoint Online Free', description: 'Convert PDF pages to editable PPTX slides. Turn PDF presentations back into PowerPoint — free, no upload required.' },
  'docx-viewer': { titleSuffix: 'View Word Documents Online Free', description: 'View Word documents directly in your browser. No Microsoft Word needed — open and read DOCX files instantly, free, no sign-up.' },
  'docx-editor': { titleSuffix: 'Edit Word Documents Online Free', description: 'Edit Word documents online without any software. Modify DOCX content in your browser — free, no upload to a server, no sign-up.' },
  'excel-viewer': { titleSuffix: 'View Excel Files Online Free', description: 'View XLSX spreadsheets in your browser. No Excel needed — open and read spreadsheet data instantly, free, no sign-up required.' },
  'csv-viewer': { titleSuffix: 'View CSV Files Online Free', description: 'View CSV files in a clean, sortable table. Open and inspect CSV data without spreadsheet software — free, no sign-up required.' },
  'csv-editor': { titleSuffix: 'Edit CSV Files Online Free', description: 'Edit CSV data in a spreadsheet-like interface. Modify, add and remove rows — free, all in your browser, no sign-up required.' },
  'csv-merge': { titleSuffix: 'Merge CSV Files Online Free', description: 'Combine multiple CSV files into one dataset. Join CSVs with matching or different columns — free, no upload to a server.' },
  'csv-split': { titleSuffix: 'Split CSV Files Online Free', description: 'Split a large CSV into multiple smaller files. Divide by row count or column values — free, all processing in your browser.' },
  'excel-to-csv': { titleSuffix: 'Convert Excel to CSV Online Free', description: 'Convert XLSX spreadsheets to CSV format. Export Excel data as plain text — free, no upload, no sign-up required.' },
  'csv-to-excel': { titleSuffix: 'Convert CSV to Excel Online Free', description: 'Convert CSV data into XLSX spreadsheet files. Import CSV data into Excel format — free, all in your browser, no sign-up.' },
  'ppt-viewer': { titleSuffix: 'View PowerPoint Online Free', description: 'View PowerPoint presentations in your browser. No PowerPoint needed — open and read PPTX files instantly, free, no sign-up.' },
  'color-palette-generator': { titleSuffix: 'Generate Color Palettes', description: 'Generate beautiful color palettes from any base color. Create harmonious schemes for design and branding — free, no sign-up.' },
  'gradient-generator': { titleSuffix: 'Create CSS Gradients Online Free', description: 'Create smooth CSS gradients with live preview. Generate linear, radial and conic gradients with custom colors — free, no sign-up.' },
  'css-gradient-generator': { titleSuffix: 'Generate CSS Gradient Code', description: 'Generate CSS linear and radial gradient code. Create gradient styles with visual preview and copy-ready CSS — free, no sign-up.' },
  'glassmorphism-generator': { titleSuffix: 'Create Glassmorphism CSS', description: 'Create frosted glass UI effects with CSS. Generate glassmorphism styles with blur, transparency and borders — free, no sign-up.' },
  'neumorphism-generator': { titleSuffix: 'Generate Neumorphism CSS', description: 'Generate soft UI neumorphism CSS styles. Create subtle shadow effects for modern interface design — free, no sign-up.' },
  'css-button-generator': { titleSuffix: 'Generate CSS Buttons Online Free', description: 'Design and generate CSS buttons with live preview. Customize colors, borders, shadows and hover states — free, no sign-up.' },
  'css-shadow-generator': { titleSuffix: 'Generate CSS Shadows Online Free', description: 'Create box-shadow CSS code with visual preview. Generate single or multiple shadows for elements — free, no sign-up required.' },
  'border-radius-generator': { titleSuffix: 'Generate Border Radius CSS', description: 'Generate border-radius CSS with visual preview. Create rounded corners for any element with custom values — free, no sign-up.' },
  'svg-viewer': { titleSuffix: 'View SVG Files Online Free', description: 'View and inspect SVG files with code preview. See SVG source and rendered output side by side — free, no sign-up required.' },
  'svg-optimizer': { titleSuffix: 'Optimize SVG Files Online Free', description: 'Minify and optimize SVG files for the web. Reduce file size by removing unused data and whitespace — free, no sign-up.' },
  'svg-to-png': { titleSuffix: 'Convert SVG to PNG Online Free', description: 'Convert SVG files to PNG images instantly. Set custom dimensions and background color — free, all in your browser, no sign-up.' },
  'png-to-svg': { titleSuffix: 'Convert PNG to SVG Online Free', description: 'Convert PNG images to SVG vector format. Trace raster images into scalable vector graphics — free, no sign-up required.' },
  'favicon-generator': { titleSuffix: 'Create Favicons Online Free', description: 'Create favicons from any image for your website. Generate multiple sizes from a single source image — free, no sign-up required.' },
  'image-placeholder-generator': { titleSuffix: 'Generate Placeholder Images', description: 'Generate placeholder images for mockups and prototypes. Set custom dimensions, colors and text — free, no sign-up required.' },
  'browser-information': { titleSuffix: 'Check Browser Info Online Free', description: 'View your browser name, version, operating system, screen resolution and capability details — free, no sign-up required.' },
  'user-agent-parser': { titleSuffix: 'Parse User Agent Strings Online Free', description: 'Parse and decode any user agent string. Extract browser, OS and device information from UA strings — free, no sign-up.' },
  'ip-address-checker': { titleSuffix: 'Check IP Address Online Free', description: 'Check your IP address and network details. View your public IP, location and connection type — free, no sign-up required.' },
  'http-header-viewer': { titleSuffix: 'View HTTP Headers Online Free', description: 'View HTTP response headers for any URL. Inspect content type, cache settings and security headers — free, no sign-up.' },
  'cookie-viewer': { titleSuffix: 'View Browser Cookies Online Free', description: 'Inspect cookies stored by your browser. View cookie names, values, domains and expiration dates — free, no sign-up required.' },
  'dns-lookup': { titleSuffix: 'Look Up DNS Records Online Free', description: 'Look up DNS records for any domain. Check A, AAAA, MX, TXT, CNAME and NS records — free, no sign-up required.' },
  'ssl-checker': { titleSuffix: 'Check SSL Certificates Online Free', description: 'Check SSL certificate details for any website. View issuer, validity, expiration and chain information — free, no sign-up.' },
  'website-screenshot': { titleSuffix: 'Capture Website Screenshots', description: 'Capture screenshots of any website URL. Set viewport size and capture full-page or viewport-only images — free, no sign-up.' },
  'open-graph-preview': { titleSuffix: 'Preview Open Graph Tags Online Free', description: 'Preview how your site looks when shared on social media. Check og:title, og:description and og:image — free, no sign-up.' },
  'url-preview': { titleSuffix: 'Preview URL Meta Tags Online Free', description: 'Preview meta tags and content for any URL. Check title, description, Open Graph and Twitter Card tags — free, no sign-up.' },
  'qr-label-generator': { titleSuffix: 'Generate QR Code Labels Online Free', description: 'Generate printable QR code labels for products and packaging. Create sheets of QR codes with custom data — free, no sign-up.' },
  'website-manifest-generator': { titleSuffix: 'Generate PWA Manifest', description: 'Generate PWA manifest files for your website. Create web app manifests with icons, theme color and display settings — free, no sign-up.' },
  'notes': { titleSuffix: 'Take Notes Online Free', description: 'Take and save notes directly in your browser. Your notes persist locally — no account, no upload, no sign-up. Free and private.' },
  'to-do-list': { titleSuffix: 'Create To-Do Lists Online Free', description: 'Create and manage tasks with a clean to-do list. Add, complete and delete tasks — your list persists locally, free, no sign-up.' },
  'pomodoro-timer': { titleSuffix: 'Pomodoro Timer Online Free', description: 'Boost focus with a Pomodoro work-break timer. Customizable work and break intervals — free, no sign-up, runs in your browser.' },
  'countdown-timer': { titleSuffix: 'Set Countdown Timer Online Free', description: 'Set a countdown to any date or event. Track days, hours, minutes and seconds remaining — free, no sign-up required.' },
  'stopwatch': { titleSuffix: 'Online Stopwatch Free', description: 'A precise stopwatch with lap timing support. Start, stop and record laps — free, no sign-up, runs entirely in your browser.' },
  'calendar': { titleSuffix: 'Online Calendar Free', description: 'View and navigate a monthly calendar. Check dates, plan ahead and see weekdays — free, no sign-up required, runs in your browser.' },
  'age-timeline': { titleSuffix: 'Visualize Life in Weeks Online Free', description: 'Visualize your life timeline in weeks. See how many weeks you have lived and how many remain — free, no sign-up required.' },
  'meeting-planner': { titleSuffix: 'Plan Meetings Across Timezones', description: 'Find the best meeting time across timezones. Compare local times for multiple cities side by side — free, no sign-up required.' },
  'timezone-converter': { titleSuffix: 'Convert Timezones Online Free', description: 'Convert times between any world timezones. Compare local times across cities — free, no sign-up required, runs in your browser.' },
  'business-day-calculator': { titleSuffix: 'Calculate Business Days', description: 'Calculate working days between two dates. Exclude weekends and holidays for accurate business day counts — free, no sign-up.' },
  'image-converter': { titleSuffix: 'Convert Images Online Free', description: 'Convert images between JPG, PNG and WEBP formats. Adjust quality and resize — free, all processing in your browser, no upload.' },
  'pdf-split': { titleSuffix: 'Split PDF Online Free', description: 'Extract pages or split a PDF into separate files. Choose specific pages or ranges — free, all processing in your browser, no sign-up.' },
  'uuid-generator': { titleSuffix: 'Generate UUIDs Online Free', description: 'Generate random UUID v4 identifiers in bulk. Create up to 1000 unique IDs for databases and apps — free, no sign-up required.' },
  'bmi-calculator': { titleSuffix: 'Calculate BMI Online Free', description: 'Calculate Body Mass Index from height and weight. Get instant BMI score with category — free, no sign-up required.' },
  'temperature-converter': { titleSuffix: 'Convert Temperature Online Free', description: 'Convert between Celsius, Fahrenheit and Kelvin. Accurate temperature conversions for cooking, science and weather — free, no sign-up.' },
  'data-storage-converter': { titleSuffix: 'Convert Data Units Online Free', description: 'Convert between bytes, KB, MB, GB, TB and PB. Understand digital storage sizes — free, no sign-up required.' },
  'remove-duplicate-lines': { titleSuffix: 'Remove Duplicate Lines Online Free', description: 'Remove duplicate lines from any text instantly. Case-sensitive or insensitive deduplication — free, no sign-up required.' },
  'json-validator': { titleSuffix: 'Validate JSON Online Free', description: 'Validate JSON and find syntax errors instantly. Get error locations and fix malformed JSON — free, no sign-up required.' },
  'sha256-hash-generator': { titleSuffix: 'Generate SHA-256 Hashes Online Free', description: 'Generate SHA-256 hashes from any text input. Compute cryptographic checksums for data integrity — free, no sign-up required.' },
  'sitemap-generator': { titleSuffix: 'Generate XML Sitemaps Online Free', description: 'Generate XML sitemaps for search engine indexing. Create valid sitemaps with URLs, priorities and change frequency — free, no sign-up.' },
  'slug-generator': { titleSuffix: 'Generate URL Slugs Online Free', description: 'Generate SEO-friendly URL slugs from any text. Convert titles to clean, hyphenated URLs — free, no sign-up required.' },
  'redirect-checker': { titleSuffix: 'Check URL Redirects Online Free', description: 'Check URL redirect chains and HTTP status codes. Trace 301, 302 and other redirects — free, no sign-up required.' },
  'pdf-merge': { titleSuffix: 'Merge PDF Files Online Free', description: 'Combine multiple PDF files into a single document. Drag and drop to reorder, merge unlimited pages — free, all in your browser, no sign-up.' },
};

export function getToolEnhancement(slug: string): Enhancement | undefined {
  return enhancements[slug];
}

export function getEnhancedTitle(tool: Tool): string {
  const enh = enhancements[tool.slug];
  if (enh) return `${tool.name} — ${enh.titleSuffix}`;
  return tool.name;
}

export function getEnhancedDescription(tool: Tool): string {
  const enh = enhancements[tool.slug];
  if (enh) return enh.description;
  return tool.description;
}
