import type { VideoToolConfig } from '@/components/video/video-tool';

export const videoToolConfigs: Record<string, VideoToolConfig> = {
  'video-compressor': { slug: 'video-compressor', label: 'Video Compressor', description: 'Compress video', accept: 'video/mp4,video/webm,video/quicktime', supportsMultiple: false, showSpeedControl: false, showRotationControl: false, showTimeRange: false, showWatermarkText: false, outputFormat: 'mp4', actionLabel: 'Compress Video' },
  'video-converter': { slug: 'video-converter', label: 'Video Converter', description: 'Convert video format', accept: 'video/mp4,video/webm,video/quicktime,video/x-msvideo', supportsMultiple: false, showSpeedControl: false, showRotationControl: false, showTimeRange: false, showWatermarkText: false, outputFormat: 'webm', actionLabel: 'Convert Video' },
  'video-trimmer': { slug: 'video-trimmer', label: 'Video Trimmer', description: 'Trim video', accept: 'video/mp4,video/webm', supportsMultiple: false, showSpeedControl: false, showRotationControl: false, showTimeRange: true, showWatermarkText: false, outputFormat: 'mp4', actionLabel: 'Trim Video' },
  'video-cutter': { slug: 'video-cutter', label: 'Video Cutter', description: 'Cut video', accept: 'video/mp4,video/webm', supportsMultiple: false, showSpeedControl: false, showRotationControl: false, showTimeRange: true, showWatermarkText: false, outputFormat: 'mp4', actionLabel: 'Cut Video' },
  'video-merger': { slug: 'video-merger', label: 'Video Merger', description: 'Merge videos', accept: 'video/mp4,video/webm', supportsMultiple: true, showSpeedControl: false, showRotationControl: false, showTimeRange: false, showWatermarkText: false, outputFormat: 'mp4', actionLabel: 'Merge Videos' },
  'video-splitter': { slug: 'video-splitter', label: 'Video Splitter', description: 'Split video', accept: 'video/mp4,video/webm', supportsMultiple: false, showSpeedControl: false, showRotationControl: false, showTimeRange: false, showWatermarkText: false, outputFormat: 'mp4', actionLabel: 'Split Video' },
  'video-rotator': { slug: 'video-rotator', label: 'Video Rotator', description: 'Rotate video', accept: 'video/mp4,video/webm', supportsMultiple: false, showSpeedControl: false, showRotationControl: true, showTimeRange: false, showWatermarkText: false, outputFormat: 'mp4', actionLabel: 'Rotate Video' },
  'video-cropper': { slug: 'video-cropper', label: 'Video Cropper', description: 'Crop video', accept: 'video/mp4,video/webm', supportsMultiple: false, showSpeedControl: false, showRotationControl: false, showTimeRange: false, showWatermarkText: false, outputFormat: 'mp4', actionLabel: 'Crop Video' },
  'video-speed-controller': { slug: 'video-speed-controller', label: 'Video Speed Controller', description: 'Change speed', accept: 'video/mp4,video/webm', supportsMultiple: false, showSpeedControl: true, showRotationControl: false, showTimeRange: false, showWatermarkText: false, outputFormat: 'mp4', actionLabel: 'Change Speed' },
  'reverse-video': { slug: 'reverse-video', label: 'Reverse Video', description: 'Reverse video', accept: 'video/mp4,video/webm', supportsMultiple: false, showSpeedControl: false, showRotationControl: false, showTimeRange: false, showWatermarkText: false, outputFormat: 'mp4', actionLabel: 'Reverse Video' },
  'mute-video': { slug: 'mute-video', label: 'Mute Video', description: 'Mute video', accept: 'video/mp4,video/webm', supportsMultiple: false, showSpeedControl: false, showRotationControl: false, showTimeRange: false, showWatermarkText: false, outputFormat: 'mp4', actionLabel: 'Mute Video' },
  'extract-audio': { slug: 'extract-audio', label: 'Extract Audio', description: 'Extract audio', accept: 'video/mp4,video/webm', supportsMultiple: false, showSpeedControl: false, showRotationControl: false, showTimeRange: false, showWatermarkText: false, outputFormat: 'mp3', actionLabel: 'Extract Audio' },
  'video-to-gif': { slug: 'video-to-gif', label: 'Video to GIF', description: 'Convert to GIF', accept: 'video/mp4,video/webm', supportsMultiple: false, showSpeedControl: false, showRotationControl: false, showTimeRange: false, showWatermarkText: false, outputFormat: 'gif', actionLabel: 'Convert to GIF' },
  'gif-to-video': { slug: 'gif-to-video', label: 'GIF to Video', description: 'Convert GIF', accept: 'image/gif', supportsMultiple: false, showSpeedControl: false, showRotationControl: false, showTimeRange: false, showWatermarkText: false, outputFormat: 'mp4', actionLabel: 'Convert to Video' },
  'video-watermark': { slug: 'video-watermark', label: 'Video Watermark', description: 'Add watermark', accept: 'video/mp4,video/webm', supportsMultiple: false, showSpeedControl: false, showRotationControl: false, showTimeRange: false, showWatermarkText: true, outputFormat: 'mp4', actionLabel: 'Add Watermark' },
  'video-thumbnail-generator': { slug: 'video-thumbnail-generator', label: 'Video Thumbnail Generator', description: 'Generate thumbnail', accept: 'video/mp4,video/webm', supportsMultiple: false, showSpeedControl: false, showRotationControl: false, showTimeRange: false, showWatermarkText: false, outputFormat: 'png', actionLabel: 'Generate Thumbnail' },
  'video-metadata-viewer': { slug: 'video-metadata-viewer', label: 'Video Metadata Viewer', description: 'View metadata', accept: 'video/mp4,video/webm', supportsMultiple: false, showSpeedControl: false, showRotationControl: false, showTimeRange: false, showWatermarkText: false, outputFormat: 'txt', actionLabel: 'View Metadata' },
  'video-metadata-remover': { slug: 'video-metadata-remover', label: 'Video Metadata Remover', description: 'Remove metadata', accept: 'video/mp4,video/webm', supportsMultiple: false, showSpeedControl: false, showRotationControl: false, showTimeRange: false, showWatermarkText: false, outputFormat: 'mp4', actionLabel: 'Remove Metadata' },
};
